VazkiiMods/Botania

src/main/resources/assets/botania/lang/nl_NL.lang

Translated almost all text to be understandable by Dutch folks.
Checked for correct references. Also checked to fit the pages.

Added Dutch translation

---

src/main/resources/assets/botania/lang/fr_FR.lang

- Small corrections
- Translated NEI Integration
- Translated parts of the Configuration
- Translated "Baubles" to "Babioles" (French equivalent)
- Translated the Message from the Elven Garde ("Elfegarde" is a somewhat fancy term for "Elven Garde")
- Translated the "Manaseer Monocle" to "Monocle du Cherche-Mana" (Had to change "Manaseer" to an equivalent of "Mana-seeker", in order to have a nice translation")
- Translated some of the Brew names to fantasy names. (Had to change Night Vision from "Owlsight" to "Shadow eye", "Fleetfeet" became "Quick run", and "Magmaskin" became "Stone skin")
- Finished the Black Lotus Page
- Took out the "Alchemising with Mana" segment, as it was redundant with the "Botanical Alchemy" just below
- Translated the "Brewing Flasks" page
(If you need to contact …

Updated french localisation

---

src/main/java/vazkii/botania/client/integration/nei/NEIBotaniaConfig.java
src/main/java/vazkii/botania/client/integration/nei/RecipeHandlerFloatingFlowers.java
src/main/resources/assets/botania/lang/en_US.lang

The nei thing!
Shows how to craft the special floating flowers in NEI: http://i.imgur.com/II79NFh.png
Also works when looking up the usage of special flowers.

Added recipe handler for crafting floating special flowers

---

src/main/resources/assets/botania/lang/en_US.lang

Fix spelling mistake

---

src/main/java/vazkii/botania/common/core/handler/ConfigHandler.java

I also made sure not to update the copyright header.

Fixed some typos & capitalization errors in the config handler.

---

src/main/java/vazkii/botania/common/Botania.java
src/main/java/vazkii/botania/common/core/handler/IMCHandler.java
src/main/java/vazkii/botania/common/item/equipment/bauble/ItemMagnetRing.java
src/main/java/vazkii/botania/common/lib/LibMisc.java

Very basic implementation of the idea mentioned in #683 using IMC.

Allow black listing of items via IMC Messages.

---

src/main/resources/assets/botania/lang/en_US.lang

Fixing grammar!

---

src/main/resources/assets/botania/lang/en_US.lang

All the Grammars!

---

src/main/java/vazkii/botania/api/internal/IManaBurst.java
src/main/java/vazkii/botania/api/mana/IManaSpreader.java
src/main/java/vazkii/botania/api/package-info.java
src/main/java/vazkii/botania/common/block/tile/mana/TileSpreader.java
src/main/java/vazkii/botania/common/entity/EntityManaBurst.java

I really need to learn github better.

Made mana bursts and mana spreader's have more addon friendly code.

---

src/main/java/vazkii/botania/common/block/subtile/functional/SubTileRannuncarpus.java

We were discussing ranges on IRC and I found this oversight in the code.

Fixed Petite Rannuncarpus's range not being affected by mana.

---

src/main/resources/assets/botania/lang/en_US.lang

Fixes, changes, new stuff in ru_RU localization
Tested locally

Updated Russian language.

---

src/main/resources/assets/botania/lang/en_US.lang

Revert "Updated Russian language."

---

src/main/java/vazkii/botania/client/core/handler/BoundTileRenderer.java

Fix using wrong y coord variable

---

src/main/java/vazkii/botania/common/item/equipment/tool/ItemTerraPick.java

This is tested and it works perfectly closes #911

Fix Thor ring giving SS achievement when using S pick

---

src/main/java/vazkii/botania/client/core/handler/BoundTileRenderer.java
src/main/java/vazkii/botania/common/crafting/ModCraftingRecipes.java
src/main/java/vazkii/botania/common/crafting/recipe/HelmRevealingRecipe.java
src/main/java/vazkii/botania/common/item/interaction/thaumcraft/ItemManasteelHelmRevealing.java

Git is hard
nuf said
all tested
less hacky
only 2 commits and they fix #766 and me being stupid

Copy/Paste from previous pull for Helm Crafting

---

src/main/java/vazkii/botania/common/item/equipment/armor/manasteel/ItemManasteelArmor.java

Check for unblockable damage types in ISpecialArmor callback. Closes #966

Armor respects unblockable damage types

---

src/main/java/vazkii/botania/common/block/tile/TileAltar.java

Added check for water when setting last recipe

---

src/main/java/vazkii/botania/common/core/handler/ConfigHandler.java
src/main/java/vazkii/botania/common/item/equipment/bauble/ItemFlightTiara.java
src/main/resources/assets/botania/lang/en_US.lang

Made the mana cost of Flügel Tiara configurable for balancing purposes.

Added a config option for configuring the mana cost of Flugel Tiara

---

src/main/java/vazkii/botania/common/block/BlockFloatingSpecialFlower.java

Add getEntry() to BlockFloatingSpecialFlower

---

src/main/resources/assets/botania/lang/en_US.lang

I'm surprised this wasn't found yet. Probably was but no one bothered to fix it.

A spelling mistake

---

src/main/java/vazkii/botania/common/block/mana/BlockSpreader.java

Closes https://github.com/Vazkii/Botania/issues/1070

Fixed lenses being consumed while in creative

---

src/main/resources/assets/botania/lang/pt_BR.lang

Music references, why can't you all have a meaning in portuguese? ¬¬'

Tweaking, fixing, adding

---

src/main/java/vazkii/botania/api/corporea/CorporeaHelper.java
src/main/java/vazkii/botania/api/corporea/ICorporeaAutoCompleteController.java
src/main/java/vazkii/botania/client/core/handler/CorporeaAutoCompleteHandler.java
src/main/java/vazkii/botania/client/core/proxy/ClientProxy.java
src/main/java/vazkii/botania/common/block/tile/corporea/TileCorporeaIndex.java
src/main/java/vazkii/botania/common/lib/LibObfuscation.java

Squashed commits. Finally figured out how to do that...

Item Autocomplete system

---

src/main/resources/assets/botania/lang/pt_BR.lang

Added Ender Bricks, Garden of Glass content and Garden of Glass Lexica entry

A (not so) fragile Garden of Glass

---

src/main/java/vazkii/botania/common/item/block/ItemBlockTinyPotato.java

I told a friend of mine about the Tiny Potato easter egg and he spelled it a little too wrong.

Forgot to put vaski

---

src/main/resources/assets/botania/lang/pt_BR.lang

Wrapping up the Functional Flora section

---

src/api/java/thaumcraft/api/IRunicArmor.java
src/main/java/vazkii/botania/common/item/equipment/armor/manasteel/ItemManasteelArmor.java
src/main/java/vazkii/botania/common/item/equipment/bauble/ItemBauble.java

after all they are made out of magically stable materials.

Add runic shielding support to all Botania armor and baubles.

---

src/main/java/vazkii/botania/common/block/ModBlocks.java
src/main/java/vazkii/botania/common/crafting/ModCraftingRecipes.java
src/main/resources/pack.mcmeta

Also added pack.mcmeta. This removes annoying FML message from logs which says "pack.mcmeta is missing"

Ore Dictionary support for recipes

---

src/main/resources/assets/botania/lang/pt_BR.lang

The new blocks and items from some versions ago, took way too long for me to update :p
- Better translations were sugested, some line were sorted
- The Dice poem was translated, doesn't rihm much though
- Rannuncarpus reference now literally mentions hand in it

Nightly localization service

---

src/main/java/vazkii/botania/client/gui/GuiAchievementsHacky.java

This will make your hacky trick work with my Better Achievements mod. Unless you want to implement some direct interaction of course. But for now this will work with v0.0.2 (which is to be released that the moment of writing this)

put setPrivate in constructor for BetterAchievements compatibility

---

.gitignore
build.gradle
src/main/java/vazkii/botania/client/core/handler/PersistentVariableHelper.java
src/main/java/vazkii/botania/client/core/proxy/ClientProxy.java
src/main/java/vazkii/botania/client/gui/lexicon/GuiLexicon.java
src/main/java/vazkii/botania/client/gui/lexicon/GuiLexiconChallenge.java
src/main/java/vazkii/botania/client/gui/lexicon/button/GuiButtonUpdateWarning.java

- Fix spelling, it’s “persistent” not “presistant”
- Update CCL, IChunkLoadTile ([required by FMP](https://gist.github.com/shadowfacts/d8a8382ec4d7474d20ae)) was added in 1.1.1.109
- Add IDEA files to .gitignore
Fixes #1340

Use MC data dir for persistent data

---

src/main/resources/assets/botania/lang/pt_BR.lang

Not even touching Dandelifeon today

Generating Flora section

---

src/main/java/vazkii/botania/common/lexicon/LexiconData.java

Fix the Mana Enchanter entry not having the last two pages
https://github.com/Vazkii/Botania/issues/1502

The missing pages

---

src/main/resources/assets/botania/lang/en_US.lang

Required to playing

---

src/main/resources/assets/botania/lang/pt_BR.lang

Added the new Pasture Seed variants
Added new Lenses
Removed lore pages

Relevant content

---

src/main/resources/assets/botania/lang/pt_BR.lang

Fixed little typos and localized stuff regarding the last two days of updates

The rewrite update

---

src/main/java/vazkii/botania/common/block/BlockModDoubleFlower.java
src/main/java/vazkii/botania/common/entity/EntityDoppleganger.java

closes #1632 and #1637 
(each bug fix is deliberately in its own commit)

Fix compatability problems with Et Futurum/JourneyMap/Chisel

---

src/main/java/vazkii/botania/common/block/tile/corporea/TileCorporeaFunnel.java

Fix Corporea Funnel attempting to put an item into another one

---

src/main/java/vazkii/botania/common/block/subtile/functional/SubTileHopperhock.java

Change hopperhock logic so that it will split a stack on the ground if the adjacent inventories only have space for *some* of it. Fixes #1683.

Allow Hopperhock to split stacks

---

web/changelog.txt

So the change is communicated properly

Update changelog to reflect actual change, not typo

---

contributing.md

The Excalibru doesn't even exist anymore, so it doesn't make sense to talk about it in contributing, as you should be working with latest version anyway

Removed references to Excaliber

---

src/main/java/vazkii/botania/common/crafting/recipe/LensDyeingRecipe.java

Fixes having extra items beyond a dye and a lens messing everything up
BTW all these PRs are tested

Fixes mana lens dyeing, closing #1708

---

src/main/java/vazkii/botania/common/block/decor/panes/BlockModPane.java

All the full glass blocks had lighting, so now these can too!

Added light to all panes, closing #1697

---

src/main/java/vazkii/botania/common/block/tile/TileAltar.java

Make CanFit (IFlowerComponent) affect items fitting into petal apothecary

---

src/main/java/vazkii/botania/common/item/rod/ItemExchangeRod.java

This allows for things like the Botanical Addons toolbelt to provide from
the tools in them while worn.
HAS BEEN ACTUALLY TESTED THIS TIME :V

Make baubles able to IBlockProvide

---

src/main/java/vazkii/botania/common/item/ItemGrassSeeds.java

Updates BlockSpawner in common/item/ItemGrassSeeds to not spread to dirt and grass blocks which have a non-air-like block above them. Added a good amount of comments and fixed all of the warnings and strange variable names (eg, "par1ItemStack" -> "itemStack") as well.
If neccessary, the non-functionality-critical parts can be removed.
Are there other block spawners where this change is neccessary?

Fix #1728 - Grass seeds will not spread to dirt/grass blocks under other blocks

---

src/main/java/vazkii/botania/common/block/decor/BlockFloatingFlower.java
src/main/java/vazkii/botania/common/block/decor/IFloatingFlower.java
src/main/java/vazkii/botania/common/block/tile/TileFloatingSpecialFlower.java
src/main/java/vazkii/botania/common/item/IFloatingFlowerVariant.java
src/main/java/vazkii/botania/common/item/ItemGrassSeeds.java

This enables Iridescent floating flowers (https://github.com/L0neKitsune/Botanical-Addons/issues/67).
Has been tested.

IslandTypes can now be added by addons

---

src/main/java/vazkii/botania/common/item/ItemGrassSeeds.java
src/main/java/vazkii/botania/common/item/equipment/tool/terrasteel/ItemTerraAxe.java

Changes the `HashMap`/`ArrayList` map used by both BlockSwappers in `ItemGrassSeed` and `ItemTerraAxe` to a `ConcurrentHashMap` and `ConcurrentHashMap`-backed set instead, which ensures that crazy threading issues do not cause esoteric NPEs and iterator invalidation.
No functional changes occurred, and performance should be equivalent.
The Terra Axe still murders trees:
The Pasture Seed still unmurders grass:

Add preemptive bugfix - Swappers now threadsafe

---

src/main/java/vazkii/botania/common/item/ItemGrassSeeds.java
src/main/java/vazkii/botania/common/item/equipment/tool/terrasteel/ItemTerraAxe.java

Followup on PR #1750, which thanks to @williewillus 's input, changes the means of concurrency to explicit sidedness instead of just concurrent data structures (as lovely as they may be).
This actually makes for a notable difference in single player, as the block swapper is no longer duplicated on both the local client and server (saving a respectable amount of duplicate computation).
As usual, proof of working for both the Terra Axe and Pasture Seed - tested both on single player and multiplayer:
Note that the solution simply employs remote checks, which works fine in principle. If I revisit this class for a clean up, however, a proper server and client proxy (where the client only handles visual effects and the server does most of the actual work) would definitely first in my priority …

Bugfix followup - Block swappers use sidedness to control concurrency

---

web/module/faq.php

If issue is not obvious: https://gyazo.com/c4657c529a337f37a3c67925e8e5e61e

Fixed license link in FAQ page.

---

src/main/java/vazkii/botania/common/crafting/ModManaInfusionRecipes.java

No more confused players!
Also fixes williewillus/Botania#91.

Newly infused mana inkwells show durability bar

---

src/main/java/vazkii/botania/common/block/subtile/functional/SubTileMarimorphosis.java

oh noes I broke the "don't use the GitHub editor" rule, truly I am horrible and this PR is completely unacceptable

Fixed Marimorphosises having incorrect downward range

---

src/main/java/vazkii/botania/common/crafting/ModCraftingRecipes.java
src/main/java/vazkii/botania/common/item/ModItems.java
src/main/java/vazkii/botania/common/lib/LibOreDict.java

Added quartz variants to ore dictionary.

Added quartz variants to Ore Dictionary

---

src/main/resources/assets/botania/lang/en_US.lang

Just spotted this while reading through the online lexicon - adjusted != adjacent

Fixed a typo

---

src/main/resources/assets/botania/lang/en_US.lang

This is the continuation of PR https://github.com/Vazkii/Botania/pull/1789 - Since I managed to rebase too far back, I got git into a really weird state where it was just easier to wipe it out and reapply the changes to a new branch. A single commit for your merging pleasure.

Lexica Botania lang_en corrections

---

src/main/java/vazkii/botania/common/block/ModBlocks.java
src/main/java/vazkii/botania/common/integration/multipart/MultipartHandler.java

Multiparts now work on both the client and the server.

---

src/main/java/vazkii/botania/common/block/ModBlocks.java
src/main/java/vazkii/botania/common/integration/multipart/MultipartHandler.java

Revert "Multiparts now work on both the client and the server."

---

src/main/resources/assets/botania/lang/zh_CN.lang

This one is a redo of #1814.
I have tested these translations in game so that they *are* suitable.

Update zh_CN.lang to latest ver.

---

src/main/java/vazkii/botania/common/crafting/ModCraftingRecipes.java

https://github.com/Vazkii/Botania/issues/1961 - I have nothing better to do today so I'm just helping people out.

Use the ore dictionary for chests in the Bauble Box recipe.

---

src/main/java/vazkii/botania/common/brew/ModBrews.java

MC 1.9 changed the potion effect numbers, this is to accommodate with those changes.

Fixes #2207

---

src/main/java/vazkii/botania/common/block/subtile/functional/SubTileHopperhock.java

Infinite Hopperhock usage fix

---

src/main/java/vazkii/botania/common/block/tile/mana/TileRFGenerator.java

I have not tested this, but it seems like the obvious fix for issue #2390.

Fix Mana Fluxfield max energy value.

---

src/main/resources/assets/botania/lang/de_de.lang

I've found two typos in de_DE.lang, so i fixed them.

fixed two typos in de_DE.lang

---

src/main/java/vazkii/botania/common/block/subtile/generating/SubTileGourmaryllis.java

Preview: https://youtu.be/XoIagtpJROw
This pairs nicely with the burp sound that was added a while back. It starts at the same speed and pitch as normal Minecraft eating, and slows/pitches down as you feed the flower more of the same food without alternating.
The motivations behind this change: it gives audiovisual feedback for the "dimishing returns" mechanic, but more importantly, I think it's funny

Gourmarillys produce chewing sounds and particles

---

README.md

It's almost 2018. Minecraft Forums are basically dead.

Update readme links to use CurseForge

---

src/main/java/vazkii/botania/common/lexicon/LexiconData.java

Fix #2486 (un-switch the Toggle and Fork luminizer recipe pages in the lexica)

---

src/main/java/vazkii/botania/common/core/helper/InventoryHelper.java

~~Admission: I didn't actually check to see if this fixed the specific problem with Quark chests, because that means downloading a new mod and putting it in my dev workspace. Which is EFFORT.~~
~~I can't imagine why it wouldn't work though *(famous last words)*~~
i have tested! scroll down

Fix #2497 by removing unneeded special-casing for TileEntityChest

---

ISSUE_TEMPLATE.md

Formatted with headers.
Formatted with linebreaks.
Added a notice section on top to give proper instructions, including directing people to the minecraft forums and reddit if they want to propose an idea because it's really easy to miss the contributing.md file.

Updating ISSUE_TEMPLATE.MD

---

build.gradle
build.properties
src/main/java/vazkii/botania/client/core/handler/CorporeaInputHandler.java
src/main/java/vazkii/botania/common/Botania.java
src/main/java/vazkii/botania/common/crafting/recipe/ArmorUpgradeRecipe.java
src/main/java/vazkii/botania/common/crafting/recipe/HelmRevealingRecipe.java
src/main/java/vazkii/botania/common/integration/thaumcraft/TCAspects.java
src/main/java/vazkii/botania/common/lib/LibMisc.java

Beta 20 includes a rather big change, an event for aspect registration, and deprecates the old ways to register aspects. This PR updates TC integration to use the event. I also tweaked some aspects and added them to lenses, and took the opportunity to fix formatting things from my last 2 PRs.
As TC6 beta 20 requires Forge 14.23.4.2705, I bumped the Forge version to that one. (I've been tempted to bump JEI as well to use Thaumic JEI during testing, to be honest).

Update TC integration to beta 21, small tweaks to aspects

---

src/main/java/vazkii/botania/common/block/tile/TileTinyPotato.java

I'm sure there's another way, but this is how the Mana Spreader does it.

Fix Tiny Potato equipment not syncing to clients

---

src/main/java/vazkii/botania/common/Botania.java

Fixes #2332. Should be self-explanatory.

Fix Botania glass blocks being unchiselable with Chisels and Bits

---

src/main/java/vazkii/botania/api/recipe/IFlowerComponent.java
src/main/java/vazkii/botania/api/recipe/RecipePetals.java
src/main/java/vazkii/botania/common/block/decor/BlockModMushroom.java
src/main/java/vazkii/botania/common/block/subtile/generating/SubTileSpectrolus.java
src/main/java/vazkii/botania/common/block/tile/TileAltar.java
src/main/java/vazkii/botania/common/crafting/ModManaAlchemyRecipes.java
src/main/java/vazkii/botania/common/item/material/ItemManaResource.java
src/main/java/vazkii/botania/common/item/material/ItemPetal.java
src/main/java/vazkii/botania/common/item/material/ItemRune.java

Vazkgoo asked for a few Botania Tweaks things to be merged in, since I'm also happy with the state of these features and think they might fit well in mainline Botania... hi, here's a PR with a million unrelated things in it :disappointed:
One thing per commit, let's go:
* A big buff to the Spectrolus (before: 300 mana/wool, now: 2400 mana per wool, **8x** increase). 
* This is one of my favorite flowers, but I always thought the mana you got from it wasn't worth the effort since you needed a huge amount of wool to do much of anything. Kind of like the Rafflowsia before it got a similar big buff
* A single piece of wool is now worth twice as much as a single piece of charcoal in an Endoflame, compared to 1/4 as much. I think this is fair, considering how hard it is to obtain, dye, and …

Some botania tweaks stuff (on discord)

---

src/main/java/vazkii/botania/client/core/handler/HUDHandler.java
src/main/java/vazkii/botania/client/core/proxy/ClientProxy.java
src/main/java/vazkii/botania/common/core/handler/ConfigHandler.java
src/main/resources/assets/botania/lang/en_us.lang

Closes #2776, and adds missing translations to config options while we're at it.

Add offline mode config option and localize config options

---

src/main/java/vazkii/botania/common/item/lens/LensRedirect.java

Fixes #2311. Per Vazkii on Discord, no, it's not intended to work like that. Includes a tiny conditional simplification because I can't resist.

Fix redirection lenses having phantom lens functionality as well

---

src/main/resources/assets/botania/recipes/petalblock_0.json
src/main/resources/assets/botania/recipes/petalblock_1.json
src/main/resources/assets/botania/recipes/petalblock_10.json
src/main/resources/assets/botania/recipes/petalblock_11.json
src/main/resources/assets/botania/recipes/petalblock_12.json
src/main/resources/assets/botania/recipes/petalblock_13.json
src/main/resources/assets/botania/recipes/petalblock_14.json
src/main/resources/assets/botania/recipes/petalblock_15.json
src/main/resources/assets/botania/recipes/petalblock_2.json
src/main/resources/assets/botania/recipes/petalblock_3.json
src/main/resources/assets/botania/recipes/petalblock_4.json
src/main/resources/assets/botania/recipes/petalblock_5.json
src/main/resources/assets/botania/recipes/petalblock_6.json
src/main/resources/assets/botania/recipes/petalblock_7.json
src/main/resources/assets/botania/recipes/petalblock_8.json
src/main/resources/assets/botania/recipes/petalblock_9.json

Fix crafting petal blocks out of mushrooms

---

src/main/java/vazkii/botania/common/entity/EntityVineBall.java

Fix vine balls placing budded/invalid vines. Closes #2819

---

src/main/java/vazkii/botania/api/BotaniaAPI.java
src/main/java/vazkii/botania/api/package-info.java
src/main/java/vazkii/botania/common/block/BlockPylon.java
src/main/java/vazkii/botania/common/core/handler/SleepingHandler.java
src/main/java/vazkii/botania/common/entity/EntityDoppleganger.java

This PR changes a few things relating to the Gaia Guardian. It fixes some cheesy bugs and cleans up the code a little bit.
* Fix #2586 by preventing sleeping during the fight and waking up any players who are.
* Change the Gaia Guardian arena check to be far stricter. It needs an unbroken floor and at least 5 blocks of clearance above the floor. [Here is a diagram](https://cdn.discordapp.com/attachments/404671932072591380/545045764934729759/unknown.png), the yellow blocks are the ones the GG checks (lowest layer = needs to be soild, other layers = needs to be nonsolid)
* A few code cleanups (add a few section comments, clean up `par1nbtTagCompound` cruft)
* Change the way the GG handles teleportation.
* Instead of sharing TP code with endermen, it simply randomly picks a point inside the …

Gaia fixes and anticheese stuff

---

src/main/java/vazkii/botania/common/entity/EntityDoppleganger.java

* Slightly less strict arena floor check.
* In every column, you need a block one *or two* blocks below the height of the beacon.
* (Or a block in both positions. But you need at least one.)
* This lets you build an arena with the beacon base placed *on* the floor, instead of inset into the floor like the multiblock preview shows, which seems to be a popular method of building the arena after all (rel: #2897)
* Minor changes to accommodate for low-floor fights.
* Block-breaking now happens only *above* the height of the beacon (== changed to >=, basically)
* GG will move one block down if the chosen TP destination is floating in the air.
* Quality of life improvements to the arena check.
* Improper pylons now show particle effects for where the pylons are supposed to go.

Gaia guardian arena stuff again, orz

---

src/main/java/vazkii/botania/common/item/equipment/armor/manasteel/ItemManasteelArmor.java
src/main/java/vazkii/botania/common/item/equipment/armor/terrasteel/ItemTerrasteelArmor.java

this should fix the whitespaces
is a clone of https://github.com/Vazkii/Botania/pull/2895, when fixed, close both of them

fix armor 2: electric boogaloo

---

src/main/resources/assets/botania/lang/ru_ru.lang

Fixed some of the incorrect translations, improved readability.

Improved russian translation

---

src/main/java/vazkii/botania/client/core/handler/ContributorFancinessHandler.java
src/main/java/vazkii/botania/common/Botania.java
src/main/java/vazkii/botania/common/block/subtile/functional/SubTileLoonuim.java
src/main/java/vazkii/botania/common/block/subtile/generating/SubTileRafflowsia.java
src/main/java/vazkii/botania/common/crafting/ModElvenTradeRecipes.java
src/main/java/vazkii/botania/common/crafting/ModPetalRecipes.java
src/main/java/vazkii/botania/common/crafting/ModRuneRecipes.java
src/main/java/vazkii/botania/common/entity/EntityDoppleganger.java
src/main/java/vazkii/botania/common/item/block/ItemBlockSpecialFlower.java
src/main/java/vazkii/botania/common/item/equipment/bauble/ItemMagnetRing.java
src/main/java/vazkii/botania/common/item/equipment/tool/elementium/ItemElementiumPick.java
src/main/java/vazkii/botania/common/item/rod/ItemGravityRod.java
src/main/java/vazkii/botania/common/item/rod/ItemTerraformRod.java
src/main/java/vazkii/botania/common/lib/ModTags.java
src/main/java/vazkii/botania/common/world/SkyblockWorldEvents.java

All mod tags are now listed in one place and all tag wrapper uses (except in api) are corrected to use them instead of making a new wrapper.

Some minor tag handling cleanup

---

src/main/java/vazkii/botania/api/item/AccessoryRenderHelper.java
src/main/java/vazkii/botania/client/core/handler/ContributorFancinessHandler.java
src/main/java/vazkii/botania/client/core/handler/LayerTerraHelmet.java
src/main/java/vazkii/botania/common/item/equipment/armor/terrasteel/ItemTerrasteelHelm.java
src/main/java/vazkii/botania/common/item/equipment/bauble/ItemBaubleCosmetic.java
src/main/java/vazkii/botania/common/item/equipment/bauble/ItemDivaCharm.java
src/main/java/vazkii/botania/common/item/equipment/bauble/ItemFlightTiara.java
src/main/java/vazkii/botania/common/item/equipment/bauble/ItemGoddessCharm.java
src/main/java/vazkii/botania/common/item/equipment/bauble/ItemItemFinder.java
src/main/java/vazkii/botania/common/item/equipment/bauble/ItemMonocle.java

...until you sneak or trapdoor yourself or swim, so obviously still needs some adjustments, and I don't know rendering much. 
All head baubles were missing the head adjustment that was done before all head baubles in 1.12.

Adjust head bauble rendering so it doesn't look as broken

---

src/main/java/vazkii/botania/common/block/tile/mana/TileSpreader.java

Fixes #3009. It's disappointingly simple.

Fix spreader binding always aiming for 0,0,0

---

src/main/java/vazkii/botania/client/core/handler/ContributorFancinessHandler.java

Fixes #3048. Yes, I did make sure the headfish renders the same.

Fix head flower render

---

src/main/java/vazkii/botania/common/block/ModFluffBlocks.java
src/main/java/vazkii/botania/common/lib/LibOreDict.java

Added OreDict names for the various quartz blocks

Added Quartz blocks to OreDict

---

src/main/java/vazkii/botania/common/block/tile/string/TileRedStringContainer.java

Two parts to this:
* If you moved the container away from its chest using something like Quark's piston pushing (looking at code, instead you could probably unload the chunk with the container but not the chest), the cap of the chest would be invalidated, destroying it and making the block incapable of doing anything not using IInventory. So we instead pack the cap in another optional. If it somehow gets destroyed without getting invalidated, the new optional gives an empty handler.
* It's all cached so we don't create however many instances of lazy optionals every tick or anything, unless the thing you used it with doesn't cache its optionals. Please review this though.
* If you replaced the chest with another TE that doesnt have the item handler cap (for example, pushing the chest with …

Fix red string container destroying caps and popping off sparks sometimes

---

src/main/java/vazkii/botania/common/crafting/recipe/SpellClothRecipe.java

Also clears work penalty now, because what is good about an unenchanted item with maxed work penalty.

Fix spellbinding cloth doing literally nothing

---

src/main/java/vazkii/botania/client/gui/bag/ContainerFlowerBag.java

Can't have i set to -1 and then access an ArrayList using that as the index immediately afterwards.

Fix ArrayIndexOutOfBoundsException in Flower Bag.

---

src/main/java/vazkii/botania/common/item/equipment/bauble/ItemIcePendant.java
src/main/resources/assets/botania/lang/en_us.json

Make the Snowflake Pendant leave a trail of snow layers wherever you go while you aren't sneaking.
Add snowflake particles to the Snowflake Pendant.
Add something about the snow layering to the Lexica Botania.

Add snow layering and particles to Snowflake Pendant

---

src/main/java/vazkii/botania/common/core/handler/SleepingHandler.java

Hi Vazkii, minimal code change sidenes check added in SleepingHelper, came across this from this issue here: https://github.com/stfwi/engineers-tools/issues/8.
It's probably faster for you to quickly add the line yourself and close the PR ;) 
Cheers, wile -

Added sideness check in SleepingHandler.trySleep().

---

src/main/java/vazkii/botania/common/item/equipment/bauble/ItemFlightTiara.java

Effectively allows it to work with skyrod

Remove Tiara's dependence on fallDistance

---

src/main/java/vazkii/botania/client/render/tile/RenderTileTinyPotato.java
src/main/resources/data/botania/patchouli_books/lexicon/en_us/entries/mana/pool.json

Fix #3232 and missing recipe in Lexica

---

src/main/java/vazkii/botania/common/entity/EntityMagicMissile.java

Avatars defend all players, players can hit mobs angry at other players when PvP is off

Refine zappyrod logic even further

---

src/main/java/vazkii/botania/common/block/ModBlocks.java
src/main/java/vazkii/botania/common/block/dispenser/BehaviourCorporeaSpark.java
src/main/java/vazkii/botania/common/block/dispenser/BehaviourSpark.java
src/main/java/vazkii/botania/common/item/ItemCorporeaSpark.java
src/main/java/vazkii/botania/common/item/ItemSpark.java

Let dispensers place sparks.

---

build.gradle
src/main/java/vazkii/botania/data/BlockstateProvider.java

`classfile` and `processing` are suppressed b/c those are Gradle upstream afaik; `deprecation`'s suppressed because otherwise we get about twenty angry messages about ITEP

Use -Xlint:all in build.gradle

---

src/main/java/vazkii/botania/common/block/subtile/functional/SubTileRannuncarpus.java
src/main/resources/assets/botania/lang/en_us.json

Make the Rannuncarpus place directional blocks facing itself.

---

src/main/java/vazkii/botania/common/crafting/RecipeTerraPlate.java

This method is used to get the ingredients. All other recipe types use them, only the new one doesn't.
This makes other mods can't get the input ingredients for the recipe. With this PR it'll be possible.

add method getIngredients() to terra plate recipe

---

src/main/java/vazkii/botania/common/item/ItemAstrolabe.java

Easier astrolabe placement

---

src/main/java/vazkii/botania/mixin/MixinServerPlayNetworkHandler.java

wow, I wonder why this goode mod stopped launching in prod?

---

src/main/java/vazkii/botania/common/crafting/RecipeBrew.java
src/main/java/vazkii/botania/common/crafting/StateIngredientHelper.java
src/main/java/vazkii/botania/common/network/PacketHandler.java

this allows an smp instance to start, generate a world and accept player connections

serverside duct-tape

---

build.gradle
src/main/java/vazkii/botania/common/integration/crafttweaker/ElvenTradeRecipeManager.java
src/main/java/vazkii/botania/common/integration/crafttweaker/ManaInfusionRecipeManager.java
src/main/java/vazkii/botania/common/integration/crafttweaker/PetalApothecaryRecipeManager.java
src/main/java/vazkii/botania/common/integration/crafttweaker/PureDaisyRecipeManager.java
src/main/java/vazkii/botania/common/integration/crafttweaker/RuneAltarRecipeManager.java
src/main/java/vazkii/botania/common/integration/crafttweaker/TerraPlateRecipeManager.java
src/main/java/vazkii/botania/common/integration/crafttweaker/actions/ActionRemoveBlockRecipe.java
src/main/java/vazkii/botania/common/integration/crafttweaker/actions/ActionRemoveElvenTradeRecipe.java
src/main/java/vazkii/botania/common/integration/crafttweaker/actions/ActionRemovePureDaisyRecipe.java

Adds CraftTweaker support for nearly all recipe types, only one missing is brews, which I may PR at a later stage.
Docs will be PR'd to the CraftTweaker Docs repo, and will be hosted on https://docs.blamejared.com
This is the script I used to test it, it should cover everything that can be done in JSON with it
Also I put CraftTweaker has a compileOnly because we don't really have an `:api` and I don't think you guys really want waste the CPU cycles loading more mods when deving, happy to change it though
```zenscript
<recipetype:botania:elven_trade>.removeRecipe(<item:botania:dragonstone>);
<recipetype:botania:elven_trade>.addRecipe("elven_trade_test", [<item:minecraft:dirt>], <item:minecraft:glass>);
<recipetype:botania:elven_trade>.addRecipe("elven_trade_multiple_test", …
```

Add CraftTweaker support

---

src/generated/resources/data/c/tags/blocks/lapis_blocks.json
src/main/java/vazkii/botania/common/block/tile/TileTerraPlate.java
src/main/java/vazkii/botania/common/lib/ModTags.java
src/main/java/vazkii/botania/data/BlockTagProvider.java

fix the terra plate multiblock

---

src/main/resources/assets/botania/lang/en_us.json

Improve ghast flavor text a bit

---

src/main/java/vazkii/botania/common/Botania.java
src/main/java/vazkii/botania/common/brew/potion/PotionBloodthirst.java
src/main/java/vazkii/botania/mixin/MixinEntitySpawnPlacementRegistry.java
src/main/java/vazkii/botania/mixin/MixinWorldEntitySpawner.java
src/main/resources/assets/botania/botania.mixins.json

Fix the Bloodthirst potion at long long last

---

src/main/java/vazkii/botania/client/render/tile/RenderTileTinyPotato.java

-Re-energize tiny potato so they can wiggle when jumping again :)))
-Fixes #3693

Fix Game-Breaking tater bug

---

src/generated/resources/data/forge/tags/blocks/mushrooms.json
src/generated/resources/data/forge/tags/items/mushrooms.json
src/main/java/vazkii/botania/common/lib/ModTags.java
src/main/java/vazkii/botania/data/BlockTagProvider.java
src/main/java/vazkii/botania/data/ItemTagProvider.java

Added the mushrooms to the relevant tags.
Am creating a sewer in my mod and want to have the Botania Mushrooms spawn in it (I use a structureprocessor to spawn mushrooms from the block tag).

Added the mushrooms to the tags.

---

src/main/java/vazkii/botania/common/advancements/AlfPortalBreadTrigger.java
src/main/java/vazkii/botania/common/advancements/AlfPortalTrigger.java
src/main/java/vazkii/botania/common/advancements/CorporeaRequestTrigger.java
src/main/java/vazkii/botania/common/advancements/DopplegangerNoArmorTrigger.java
src/main/java/vazkii/botania/common/advancements/LokiPlaceTrigger.java
src/main/java/vazkii/botania/common/advancements/ManaGunTrigger.java
src/main/java/vazkii/botania/common/advancements/RelicBindTrigger.java
src/main/java/vazkii/botania/common/advancements/UseItemSuccessTrigger.java

This is required for me to add Botania compat to [JEA](https://www.curseforge.com/minecraft/mc-mods/jea).

Make criterion instances public and add getter methods

---

Jenkinsfile

I saw a build 12 days ago, so it gets a PR

Future proof Jenkinsfile

---

src/generated/resources/assets/botania/models/tiny_potato/eutrotater.json
src/main/java/vazkii/botania/data/TinyPotatoModelProvider.java

Add "eutrotater" alias for wire tater model

---

src/main/java/vazkii/botania/common/block/mana/BlockSpreader.java

Found on discord. would have caused issues if making lenses stackable

(1.17.x-fabric) fix tiny spreader regression

---

src/main/java/vazkii/botania/common/block/mana/BlockForestDrum.java
src/main/java/vazkii/botania/common/block/subtile/functional/SubTileBergamute.java
src/main/java/vazkii/botania/common/item/ItemHorn.java
src/main/resources/assets/botania/lang/en_us.json
src/main/resources/assets/botania/lang/ja_jp.json
src/main/resources/assets/botania/lang/pt_br.json
src/main/resources/assets/botania/lang/zh_cn.json
src/main/resources/data/botania/patchouli_books/lexicon/en_us/entries/functional_flowers/bergamute.json

Backport bergamute drum deadzone to 1.16
