VazkiiMods/Botania

src/main/java/vazkii/botania/client/core/handler/LightningHandler.java

LightningHandler.onRenderWorldLast() modifies the model/view matrix and should therefore save and restore it. Actually, it introduces round-off errors into the model/view matrix by translating to world coordinates and back (calls to GL11.glTranslated()) which are proportional to the world coordinates' values (distant coordinates like 29 million introduce quite significant errors). Not restoring the matrix therefore makes it hard for other mods to do rendering correctly at distant coordinates.
This fixes issue #531.

Added glPushMatrix/glPopMatrix-pair to LightningHandler.

---

src/main/java/vazkii/botania/api/BotaniaAPI.java
src/main/java/vazkii/botania/api/package-info.java

It seemed easier this way than to include the Botania API to only call one of code.

Add DarkOre to OreChid weights

---

src/main/java/vazkii/botania/common/block/BlockModDoubleFlower.java

BlockDoublePlant overrides the color multiplier for specific meta values (ferns and grass).  This restores the default multiplier for better compatibility with mods.  E.g., mine.

Restore default color multiplier for tall flowers

---

src/main/resources/assets/botania/lang/en_US.lang

I noticed that Aries was spelled incorrectly on the Eye of the Flugal, so I fixed it.

Fix Star Signs Typo

---

src/main/java/vazkii/botania/common/block/tile/TileAltar.java

Fixes KitchenCraft seeds not working with the apothecary

Use the stack sensitive unloc name in seed matcher

---

web/module/license.php

Considering the previous license was Share-Alike, I doubt, though I acknowledge that I may be wrong in doubting, that this loophole's existence is intentional, considering it allows trivial bypassing of the original clause.

Close loophole in open-source clause of license

---

src/main/resources/assets/botania/lang/en_US.lang
src/main/resources/assets/botania/lang/fr_FR.lang
src/main/resources/assets/botania/lang/ko_KR.lang
src/main/resources/assets/botania/lang/zh_TW.lang

Fix typo in lang files for botania.page.cocoon0. If this PR is incorrect in any way, the typo is simply "Carpice" in *.lang.

Typo in Lexica entry for Cocoon of Caprice

---

src/main/java/vazkii/botania/common/block/subtile/functional/SubTileHopperhock.java

This commit should make Hopperhocks check all 6 sides for output inventories, rather than just the 4 cardinal directions. This is useful for floating hopperhocks, and for placing an inventory above a hopperhock.

Make Hopperhocks check all 6 sides for chests

---

src/main/java/vazkii/botania/api/BotaniaAPI.java

Closes #1265.
Weights are based on generation notes here: http://teamcofh.com/docs/thermal-foundation/world-generation/ores/

Implement a couple of Thermal Foundation ores in the Orechid

---

.gitignore
src/main/java/vazkii/botania/api/BotaniaAPI.java
src/main/java/vazkii/botania/common/block/ModBlocks.java
src/main/java/vazkii/botania/common/item/lens/LensPaint.java

Should fix the issue vazkii flagged in the last build.  ModBlocks get registered in the ModBlocks.init method instead of the BotaniaAPI.  Vanilla block still get registered in the BotaniaAPI.  Tested and works for all registered blocks.

Painting the town:  Adding Paintslinger API support

---

src/main/java/vazkii/botania/common/core/helper/InventoryHelper.java

The 2 variables are always assigned in the code below - so the initial assignment is not needed.

avoid unnecessary object allocation

---

src/main/java/vazkii/botania/api/mana/ICompositableLens.java
src/main/java/vazkii/botania/common/crafting/recipe/CompositeLensRecipe.java
src/main/java/vazkii/botania/common/item/lens/ItemLens.java

this will allow ILens instances that aren’t ItemLens to combine with other ILens instances
I squashed it... >.>

make ItemLens combination checking more generic (ICompositableLens)

---

src/main/java/vazkii/botania/common/item/equipment/bauble/ItemWaterRing.java

Setting the player's air to zero stops them from drowning until next tick, where it gets reset again. Added line (and indentation, never forget the indentation :wink:) to fix.

Fix #1588: chordata ring stops player from drowning with no mana.

---

src/main/java/vazkii/botania/common/block/BlockCamo.java

Before, blocks which required meta colors for determining their render
color would use the meta of the Platform itself.
Has been tested.

Make the render color for camo blocks work with meta

---

src/main/java/vazkii/botania/common/crafting/ModCraftingRecipes.java

the code was copy-pastaed from the addStairsAndSlabs helper function to
hack in oredict support, feel free to just add it to the helper function
if you want though. Looking at other Botania code, this is what comes to
mind though.
see #1703
There is also a very big problem that I marked with a comment that says
"very big problem", where on many many different stone types (end,
metamorph, 1.8) the recipe for stone bricks and for chisled is the same,
so usually you can't craft chisled.
sorry for long commit message

Add oredict support 1.8 stone recipes, closes #1660

---

src/main/java/vazkii/botania/common/item/rod/ItemExchangeRod.java

Corrects the issue where the Rod of Shifting Crust would not replace blocks surrounded by snow or other specific non-opaque cubes (eg, slabs). Blocks are checked for visibility by checking if there are any adjacent blocks which do not have an adjacent solid side.

Fix #1724 - Slabs and snow don't prevent Rod of Shifting Crust replacement

---

src/main/java/vazkii/botania/common/item/equipment/tool/terrasteel/ItemTerraAxe.java

This fixes the subtly buggy, existing breadth first search implementation by replacing it with a much more rigorous Djikstra-based Breadth First Search (which optimizes use of available range). The axe will now take advantage of the full 32 block range and respect leaves as reducing range to 3 properly, and will no longer eat entire canopies. This also comes with a nice speed boost, as only 1 block swapper needs to be created and the search can be done in amortized O(nlogn) time (where n is the number of candidate blocks).
Here are some pictures of the results:
An unassuming jungle:
Complete destruction of two trees, save some dangling leaves - previously, the top part of the tree would remain:
Another example on some poor, poor Spruce trees:
No effects on unconnected trees.
As you can …

Fix #1700 - Terra Axe strictly follow 32 block range and leaf logic

---

src/main/java/vazkii/botania/common/item/ItemGaiaHead.java

Replaces the lovely copypasta in `common/item/ItemGaiaHead.java` with more idiomatic Forge code, and with comments, too! The code is functionally identical, but uses `ForgeDirection` and looks prettier.
As usual, a lovely few pictures to show that you can still place Gaia Skulls just fine:
You can't place Gaia Skulls on the ceiling as well, maintaining previous functionality.
(Also, the code was properly cleaned up this time and extra whitespace removed).

Clean up common/item/ItemGaiaHead.java

---

src/main/java/vazkii/botania/api/item/IBaubleRender.java
src/main/java/vazkii/botania/common/item/equipment/bauble/ItemBaubleCosmetic.java

This fixes issue #1726, by adjusting the offset for rendering cosmetics from `1.62F` to `1.68F`. It also fixes the rendering of two items (Orange Shades and Groucho Glasses, by modifying their Y-offsets) so they align with the player's eyes properly.
Screenshots:
Offsets on crouch and head rotation work as they did previously. Comments welcome.

Fix #1726 - Accessories on other players now render in the proper position

---

src/main/java/vazkii/botania/common/item/equipment/bauble/ItemSpeedUpBelt.java

This provides the straightforward solution as outlined in #1722, by allowing the client to also handle slowdowns. The existing code allowed the client to handle the actual speedup, but prevented it from reseting the speed as well due to a remote server check. The actual origin of the bug is related to `Entity.moveForward` always being `0.0F` on the server, but the fix for it is nontrivial and this will work as a working solution in the meanwhile.
With this patch, the sash properly resets it's speed both on the client and the server if the user stops for a few moments. The sash speeds up properly as it already has been.
Comments welcome.

Hotfix #1722 - Allow client to control sash speedup and slowdown

---

src/main/java/vazkii/botania/common/item/ItemManaTablet.java

Makes Mana Tablet durability bar actually use `showDurabilityBar` and `getDurabilityForDisplay` instead of the deprecated `getDisplayDamage`; as `getDisplayDamage` is no longer used, damage differences can be removed entirely (so no more item stack damage 1 to 1000).
In order to ensure compatibility with previous releases, `getDamage` is overridden to ensure that all mana tablets have a damage value of 0.
Some examples of it working with storage drawers:
Before placing in drawer:
In drawer:
After:
(From left to right: empty, semi-full, full, and creative)

Fix #1749 - Mana Tablets no longer lose durability in storage drawer

---

src/api/java/com/jaquadro/minecraft/storagedrawers/api/inventory/IDrawerInventory.java
src/api/java/com/jaquadro/minecraft/storagedrawers/api/inventory/SlotType.java
src/api/java/com/jaquadro/minecraft/storagedrawers/api/storage/IDrawer.java
src/api/java/com/jaquadro/minecraft/storagedrawers/api/storage/IDrawerGroup.java
src/api/java/powercrystals/minefactoryreloaded/api/IDeepStorageUnit.java
src/main/java/vazkii/botania/api/corporea/CorporeaHelper.java
src/main/java/vazkii/botania/api/corporea/CorporeaRequest.java
src/main/java/vazkii/botania/api/corporea/IWrappedInventory.java
src/main/java/vazkii/botania/api/internal/DummyMethodHandler.java
src/main/java/vazkii/botania/api/internal/IInternalMethodHandler.java
src/main/java/vazkii/botania/common/Botania.java
src/main/java/vazkii/botania/common/core/handler/InternalMethodHandler.java
src/main/java/vazkii/botania/common/integration/corporea/WrappedDeepStorage.java
src/main/java/vazkii/botania/common/integration/corporea/WrappedIInventory.java
src/main/java/vazkii/botania/common/integration/corporea/WrappedInventoryBase.java
src/main/java/vazkii/botania/common/integration/corporea/WrappedStorageDrawers.java

Added wrapper around IInventory for integration with different storage systems. Used this for Storage Drawers and JABBA (general Deep Storage API).
I had to include Deep Storage API in Botania, which is quite ugly :-( But it will add mass support for all inventories using this API, which is apparently plenty.
TODO:
I don't have correct formatter for Botania - formatting may be off.

Added support for StorageDrawers and Deep Storage API

---

src/main/java/vazkii/botania/client/render/tile/RenderTileFloatingFlower.java
src/main/java/vazkii/botania/common/block/decor/IFloatingFlower.java

Derivative classes can use it (allows for rainbow floating flowers)
This is something Botanical Addons requires for one of its Iris Seed variants

Add a color function to the RenderTileFloatingFlower

---

src/main/java/vazkii/botania/api/mana/ManaItemHandler.java
src/main/java/vazkii/botania/api/mana/ManaItemsEvent.java
src/main/java/vazkii/botania/api/package-info.java
src/main/java/vazkii/botania/client/core/handler/HUDHandler.java

**Changes:**
Adds two helper functions, getManaItems() and getManaBaubles(), in ManaItemHandler so that the code for gathering mana-storing items no longer needs to be repeated in ManaItemHandler and HUDHandler and to enable ManaItemsEvent to function.
getManaItems() gathers mana-storing items from the player's base inventory, as base Botania does. The new code here calls ManaItemsEvent to enable mods to pass (or remove) mana-storing items from their own inventories.
getManaBaubles() gathers mana-storing items from the player's baubles inventory. The reason this function is separate from getManaItems() is because Botania code requires sendBaubleUpdatePacket to be called when a mana-storing bauble is accessed. sendBaubleUpdatePacket needs a slot number as a param, so I had to make this. …

Added ManaItemsEvent

---

src/main/java/vazkii/botania/common/item/equipment/tool/ToolCommons.java

I know you are pretty strict about pull requests, so feel free to delete this, I simply thought that my explanation for the issue here:
https://github.com/Vazkii/Botania/issues/1975
is hard to understand because github doesn't have the best formatting.
This pretty much fixes the nbt data loss because the tileEntity was already deleted at the point where you were retrieving it.
Built and tested locally, works.

Fixed aoe tool referencing already removed tileEntity

---

src/main/java/vazkii/botania/common/block/tile/TileAlfPortal.java

Allows using a Lexica as an ingredient in Alfheim Portal recipes.
This is required for my Elven Charter addon which uses the Lexica to track who's used the current trade and who hasn't.
To address willie's concerns on my original PR for this (williewillus/Botania#421), `isElvenItem` doesn't work for this without modifying and changing the meaning of the method. Currently `ItemLexicon.isElvenItem` return `true` if the elven knowledge has been unlocked, so the Lexica can't be thrown back into the portal. This would require special casing in the Portal or changing the fundamental meaning of `isElvenItem`, potentially breaking anything else that uses it.

Allow inserting elven lexica into the portal

---

src/main/java/vazkii/botania/common/block/tile/TileEnchanter.java

`ench.func_191560_c` returns `true` if the two enchantments are mutually compatible.
Fixes #2188

Fix Mana Enchanter only applying one enchanted book

---

src/main/java/vazkii/botania/common/block/subtile/functional/SubTileOrechid.java

Simple check to ensure that the ore item returned by the ore dictionary is a subclass of ItemBlock

Restrict ores from the ore dictionary to only those that are blocks.

---

src/main/java/vazkii/botania/common/block/decor/BlockElfGlass.java
src/main/java/vazkii/botania/common/block/decor/BlockManaGlass.java

- I saw that BlockGlass was using the method isFullCube and Botania was using isFullBlock, so I switched it and it seems to have fixed the issue, #2272.
- Removed redundant overwrite of isFullBlock in BlockElfGlass.
Before:
After:

Fixes Managlass and Elfglass transparencies, Fixes #2272

---

src/main/java/vazkii/botania/client/fx/FXSparkle.java

Particles now wiggle along each secondary axis independently.

Fix #2322 - particle bias

---

src/main/java/vazkii/botania/common/block/ModBlocks.java

The issue was that mini flower recipes were being registered before the specialFlower block item was registered, so the recipes for mini flowers were defaulting to having an input and output of Air blocks, breaking all the alchemy recipes.
Fixes #2337.

Fixes the alchemy catalyst eating everything and never working

---

src/main/java/vazkii/botania/common/crafting/ModCraftingRecipes.java

Viewing the recipe for the Band of Aura in the Lexicon was failing - it seems this recipe was accidentally missed in `ModCraftingRecipes` when moving recipes to JSON.

Fixes the crash when trying to view the recipe for the Band of Aura

---

src/main/java/vazkii/botania/client/gui/lexicon/GuiLexicon.java
src/main/java/vazkii/botania/client/gui/lexicon/GuiLexiconChallenge.java
src/main/java/vazkii/botania/client/gui/lexicon/GuiLexiconChallengesList.java
src/main/java/vazkii/botania/client/gui/lexicon/GuiLexiconEntry.java
src/main/java/vazkii/botania/client/gui/lexicon/GuiLexiconIndex.java

This should fix the following weird shaking when using the Lexicon:
- The tooltip that indicates that you can hold Shift to get more information about an entry should no longer flash in and out of view.
- The tooltip that is displayed when you hold Shift should no longer pop into and out of existence, and it should stay at a fixed width instead of shaking.
- The shadow placed behind entries in the Lexicon when you mouse over them should no longer shake on the right edge of the Lexicon.

Fixes the shaking mouse-over elements in the Lexicon.

---

src/main/java/vazkii/botania/common/block/BlockAnimatedTorch.java
src/main/java/vazkii/botania/common/block/subtile/functional/SubTileDaffomill.java
src/main/java/vazkii/botania/common/block/tile/TileAnimatedTorch.java

Just a small usability and convenience tweak. They used to always face north when you placed them, now they face away from the player, like a repeater.
This is my first PR ever so please nitpick. I hope I'm doing this right.

Daffomills and anime torches face away from the player when placed

---

src/main/java/vazkii/botania/common/item/equipment/bauble/ItemTravelBelt.java

1.25F is player jump height, which is what should ideally be used for step assist. This allows a player to step up to places where they would otherwise be able to jump to, such as a block with 2 layers of snow on top of it.
If there are other places in the code where this needs changing, feel free to close this PR and I'll open an issue for it to be dealt with later.

Fix incorrect step assist height

---

src/main/java/vazkii/botania/common/block/tile/mana/TileSpreader.java

The TileSpreader class now overrides TileEntity's rotate() and mirror() methods, so if a mana spreader is part of a structure saved via vanilla Minecraft's structure block and that structure is then loaded with rotation or reflection applied, the direction the spreader is pointing is adjusted accordingly.

Support rotation of structures containing mana spreaders

---

src/main/java/vazkii/botania/api/mana/ManaItemHandler.java

This commit changes the two calls to the deprecated getFullDiscountForTools method in requestManaForTool and requestManaForToolExact to the newer ItemStack-sensitive one. Otherwise, the stack is always null.

Fixed usages of deprecated getFullDiscountForTools method

---

src/main/java/vazkii/botania/common/item/equipment/armor/elementium/ItemElementiumArmor.java
src/main/java/vazkii/botania/common/item/equipment/tool/elementium/ItemElementiumAxe.java
src/main/java/vazkii/botania/common/item/equipment/tool/elementium/ItemElementiumPick.java
src/main/java/vazkii/botania/common/item/equipment/tool/elementium/ItemElementiumShears.java
src/main/java/vazkii/botania/common/item/equipment/tool/elementium/ItemElementiumShovel.java
src/main/java/vazkii/botania/common/item/equipment/tool/elementium/ItemElementiumSword.java

This fixes https://github.com/Vazkii/Botania/issues/2646 
I assumed that Elementium was the correct material to repair the tools instead of manasteel because the tools were made from Elementium, also Elementium is used to repair the armor instead of manasteel.

Elementium Tools now repair with Elementium

---

src/main/java/vazkii/botania/api/BotaniaAPI.java
src/main/java/vazkii/botania/api/wiki/WikiHooks.java

I noticed a lot of outdated links in the wiki provider list, going to sites that are gone or taken over by some shady stuff, and decided to clean that up a bit.
No new wikis were added - basically the main reason I did this was being afraid any users would accidentally use the lexica on a block and land on a bad site.
Summary of changes:
* Gamepedia is now purely on HTTPS
* Lowercased the modids. Didn't change that the providers lowercase the modid as well - what if someone's using the API expecting that? (as if anyone uses this feature).
* Buildcraft's wiki previously used doesn't exist anymore.
* Ars Magica 2, Pneumaticraft - the site was taken over last time I checked.
* Witchery, Gany's mods - those mods seem to be entirely dead. 
* Steve's Carts, Random Things - both were on …

Clean up and update wiki providers

---

src/main/resources/assets/botania/recipes/_constants.json
src/main/resources/assets/botania/recipes/bellows.json
src/main/resources/assets/botania/recipes/corporeaindex.json
src/main/resources/assets/botania/recipes/endereyeblock.json
src/main/resources/assets/botania/recipes/enderhand.json
src/main/resources/assets/botania/recipes/flighttiara_0.json
src/main/resources/assets/botania/recipes/forestdrum_0.json
src/main/resources/assets/botania/recipes/forestdrum_1.json
src/main/resources/assets/botania/recipes/forestdrum_2.json
src/main/resources/assets/botania/recipes/garden_of_glass/end_portal_frame.json
src/main/resources/assets/botania/recipes/keepivy.json
src/main/resources/assets/botania/recipes/knockbackbelt.json
src/main/resources/assets/botania/recipes/lens_22.json
src/main/resources/assets/botania/recipes/manavoid.json
src/main/resources/assets/botania/recipes/starfield.json
src/main/resources/assets/botania/recipes/thornchakram_0.json
src/main/resources/assets/botania/recipes/tornadorod.json
src/main/resources/assets/botania/recipes/travelbelt.json

Replaces leather, feathers, obsidian, paper and vines with their oredict entries in crafting recipes. (Except the vine ball, as that wouldn't make too much sense).
Made mostly because I noticed some items taking only vanilla leather when all I had access to was oredicted replacements.
I did notice most brew recipes don't use oredict at all, but I left them alone as I didn't know how appropriate was replacing their ingredients.

Use ore dictionary ingredients in more recipes

---

src/main/java/vazkii/botania/common/block/tile/TileCocoon.java

A minor nitpick PR, I guess.
Llamas were added in 1.11, while parrots were added in 1.12.
Both of them are a rare pet and so should be available from the cocoon. I assume the only reason they were not available is that no one actually thought about it. The last functionality change of the cocoon was adding shulker spawning in early 1.11.
This ensures that GoG players will be capable of obtaining these mobs, possibly giving access to some parts of other mods as well.
This does make the other rare mobs slightly rarer, but while I did think about buffing the rare mob chance slightly, I doubt this will matter too much in the long run as reliably getting a pair of all the rare mobs already requires a decent investment, but I am open to tweaking the numbers.
Oh, there were some talks in …

Add llamas and parrots to the cocoon's rare animal spawns

---

src/main/java/vazkii/botania/common/network/PacketBotaniaEffect.java

Server mate encountered a crash with a NullPointerException at the indicated line. It appears this case of the switch block is missing the entity null check, since the other cases do have them.

Add missing null check in PacketBotaniaEffect

---

src/main/java/vazkii/botania/api/corporea/CorporeaHelper.java
src/main/java/vazkii/botania/common/block/corporea/BlockCorporeaCrystalCube.java
src/main/java/vazkii/botania/common/block/corporea/BlockCorporeaRetainer.java
src/main/java/vazkii/botania/common/block/tile/corporea/TileCorporeaCrystalCube.java
src/main/java/vazkii/botania/common/block/tile/corporea/TileCorporeaRetainer.java

This PR:
* adds a cute helper function in `CorporeaHelper` to get a signal strength 0-15 from a corporea request size 0-16384, using the usual "each step up needs double the size" method,
* modifies the corporea crystal cube to use that helper function to determine its comparator strength
* modifies the corporea retainer to use that helper function to determine its comparator strength, as opposed to the previous "15 if there is any pending request at all, ever" behavior

Corporea retainers use richer signal strength depending on request size (but better)

---

src/main/java/vazkii/botania/common/item/block/ItemBlockSpecialFlower.java

Replaces the tooltip containing the creator mod's modid with an override for the method returning it,  allowing mods like JEI to show the mod that actually added the flower and return it in mod searches, like
Forge's universal bucket already does with mod fluids.
Example, using a flower from Incorporeal:

Implement getCreatorModId on the flower item

---

src/main/resources/assets/botania/models/item/cosmetic32.json

Very important
Before: 
After: 
Yeah it clips the floor a bit, but moving it up any farther makes it look weird. :V

Fix positioning of the thinking hand when you put it on a tiny potato

---

src/main/java/vazkii/botania/client/render/tile/RenderTileTinyPotato.java

Also adjusts the placement of any blocks on the top side of the potato
such that they rest flatly on the potato's head.

Resize and reorient Tiny Potatoes held as equipment by other Tiny Potatoes

---

src/main/java/vazkii/botania/api/recipe/RecipeElvenTrade.java
src/main/java/vazkii/botania/common/block/tile/TileAlfPortal.java

Fixes #2403 by checking if the item actually is a part of any recipe. Also simplifies the oredict stack check in the elven trade recipe logic.
Possibly mitigates #2669, as recipe checks are a bit simplified to not create stack copies (posting capability events and stuff) and the portal will not check items with no uses more than once. Of course if some mod/modpack developer adds a recipe that takes different items you are able to fill the portal tile with a lot of one component of the recipe, but this will make it rarer.
Also now includes a dumb reference to two things at once. I have done nothing but teleport bread for 5 minutes to test it. If you don't want to include it, don't pull the second commit.

Fix Alfheim portal storing items not used in recipes

---

src/main/java/vazkii/botania/common/block/tile/TileAlfPortal.java

Fixes #2725. I swear I am somewhat competent and just forgot that the lexicon is a dumb hardcoded special case. Can we move all Botania recipes to proper ingredients and stuff yet?

Fix the portal not returning the lexicon

---

src/main/java/vazkii/botania/client/integration/jei/JEIBotaniaPlugin.java
src/main/java/vazkii/botania/client/integration/jei/brewery/BreweryRecipeCategory.java
src/main/java/vazkii/botania/client/integration/jei/brewery/BreweryRecipeWrapper.java
src/main/java/vazkii/botania/common/item/brew/ItemBrewBase.java

* Add subtype interpreters to make looking up specific brew recipes less annoying - clicking on "Vial of Fleetfeet" will show you only that specific recipe and not all of them.
* Add blood pendants and incense sticks to the brew recipe wrapper, so that they can be looked up too.
* Add locking of the other ingredient, so that when an item is focused, the other ingredient does not change to the items that don't fit (eg. you looked up the flask of fleetfeet, the input no longer swaps between vials and flasks, but stays locked to the alfglass flask - this was made more obvious by adding pendants and sticks).

Improve handling of brews in JEI

---

build.gradle
src/main/java/vazkii/botania/client/core/handler/CorporeaInputHandler.java
src/main/java/vazkii/botania/client/integration/jei/JEIBotaniaPlugin.java
src/main/java/vazkii/botania/common/lib/LibMisc.java

Bumps required JEI version to 4.13.1.220, which added the required hook (see mezz/JustEnoughItems#1374). If you want to wait a bit until a stable release is made with this hook to merge, I'll be fine with that.
This might not seem like much, but after playing a bit with Corporea as a storage solution, I think I will cherrypick this and make a custom build for personal use, just to use this - it is a giant difference when you don't have to leave the crafting screen to type in the names and request all the items.

Add JEI recipe gui support for the corporea request key

---

build.gradle

Probably fixes #2536.
This PR should make it easier to dep on Botania with Maven:
* The main jar file it builds now no longer contains the stuff it should exclude, and has a proper manifest.
* Removed the possibility of building a deobf jar, it interferes with deobfCompile which is ugly with mismatching mappings
* Added a source jar so that IDEs can pull the sources.
I say "probably" and "attempt" because I am not 100% sure it will work despite all the testing I did and the few dozens of local maven deploys I've done.

Attempt to fix ATs in jar manifest, and add sources jar

---

src/main/java/vazkii/botania/common/item/ItemVirus.java

Fixes #2777. Seems like Willie kinda skipped over what that method was actually doing when updating the mod to 1.11 or something (in 641dc804900b2ddd5eb3c06161f7af0b537f9860).
Instead of setting the age to 0, the age is copied, just in case some mod allows you to have tamed foals (like Astral Sorcery did before a perk overhaul), or even NBT editing through external tools or `/entitydata`.

Fix horse viruses replacing attributes and turning horses into babies

---

src/main/java/vazkii/botania/common/Botania.java
src/main/java/vazkii/botania/common/integration/thaumcraft/TCAspects.java

* Add brew aspects, generated from the potion's ingredients similiarly to vanilla potions.
* Add Spectrolus aspects, as I missed that one...
* Tweak a few aspect lists.
* Move TC brew recipes to init - registering them in postinit was too late to assign aspects to the brew, as aspect registration is done in Thaumcraft's postinit which runs earlier. Should not have any side effects.
* Replace wood and stone stacks with their aspects, avoids livingwood having just Victus in some modpacks.
* Reduce the amount of wildcard metadata, which can rarely cause some minor issues with items not having expected aspects and is just unnecessary for many things.
* Remove aspects from entities that are just entity form of items. I was getting annoyed around Corporea sparks when using my Thaumometer.
Beta …

Tweaks to Thaumcraft integration

---

src/main/java/vazkii/botania/common/core/handler/ConfigHandler.java
src/main/java/vazkii/botania/common/entity/EntityManaBurst.java
src/main/resources/assets/botania/lang/en_us.lang

Mana spreader code is lovely as we all know so I'd like to get a few more eyes on this, if at all possible? (And someone who knows how to use a profiler would be really nice, ha!)
This PR:
* caps the maximum mana burst beam-scan distance to 400 ticks into the future, preventing big lags from https://github.com/Vazkii/Botania/issues/2787
* This changes gameplay behavior but nobody will actually care
* stops beam-scan mana bursts from searching for entities (this information was simply thrown away, resulting in lots and lots and lots of wasted calls to `getEntitiesWithinAABBExcludingEntity`)
* The Tripwire lens still works btw
* stops beam-scan mana bursts from sending "pings" to the mana spreader - this information was also simply thrown away, resulting in a lot of useless calls to …

Tentative mana spreader path tracing optimizations

---

src/main/java/vazkii/botania/common/lexicon/page/PagePetalRecipe.java

Fixes #2654. The solution was pretty simple, not checking if the shift key is held to determine the item index in the ingredient. The variable used in that was also changed to be clearer about the purpose.

Fix Lexica rotating item config not swapping usable items in recipes

---

src/main/java/vazkii/botania/common/item/equipment/bauble/ItemMagnetRing.java

* Items with pickup delay >40 ticks will be ignored (closes #2648). 40 ticks is the typical delay from death drops and the longest one in survival vanilla, so I figured it's a decent condition (I'm fine with changing it though).
* Ignore AE2 seeds with their new name.
* Make the blacklist actually usable and not crash when added to with IMC. Seems like this was broken since the very day it was added as it was using Arrays.asList at the start and then much later replaced with ImmutableList.

Make magnet ring respect pickup delays and tweak the blacklist

---

.gitignore
src/main/java/vazkii/botania/client/integration/jei/JEIBotaniaPlugin.java
src/main/java/vazkii/botania/client/integration/jei/brewery/BreweryRecipeCategory.java
src/main/java/vazkii/botania/client/integration/jei/brewery/BreweryRecipeWrapper.java
src/main/java/vazkii/botania/client/integration/jei/crafting/AncientWillRecipeWrapper.java
src/main/java/vazkii/botania/client/integration/jei/crafting/CompositeLensRecipeWrapper.java
src/main/java/vazkii/botania/client/integration/jei/crafting/SpecialFloatingFlowerWrapper.java
src/main/java/vazkii/botania/client/integration/jei/crafting/TerraPickTippingRecipeWrapper.java
src/main/java/vazkii/botania/client/integration/jei/elventrade/ElvenTradeRecipeCategory.java
src/main/java/vazkii/botania/client/integration/jei/elventrade/ElvenTradeRecipeWrapper.java
src/main/java/vazkii/botania/client/integration/jei/manapool/ManaPoolRecipeCategory.java
src/main/java/vazkii/botania/client/integration/jei/manapool/ManaPoolRecipeWrapper.java
src/main/java/vazkii/botania/client/integration/jei/orechid/OrechidIgnemRecipeCategory.java
src/main/java/vazkii/botania/client/integration/jei/orechid/OrechidIgnemRecipeWrapper.java
src/main/java/vazkii/botania/client/integration/jei/orechid/OrechidRecipeCategory.java
src/main/java/vazkii/botania/client/integration/jei/orechid/OrechidRecipeWrapper.java
src/main/java/vazkii/botania/client/integration/jei/petalapothecary/PetalApothecaryRecipeCategory.java
src/main/java/vazkii/botania/client/integration/jei/petalapothecary/PetalApothecaryRecipeWrapper.java
src/main/java/vazkii/botania/client/integration/jei/puredaisy/PureDaisyRecipeCategory.java
src/main/java/vazkii/botania/client/integration/jei/puredaisy/PureDaisyRecipeWrapper.java
src/main/java/vazkii/botania/client/integration/jei/runicaltar/RunicAltarRecipeCategory.java
src/main/java/vazkii/botania/client/integration/jei/runicaltar/RunicAltarRecipeWrapper.java
src/main/java/vazkii/botania/common/item/block/ItemBlockSpecialFlower.java

* Clean up all the deprecation and other compiler warnings in the plugin
* Fix indentation in the orechid JEI stuff
* Add wrappers for: terra shatterer tipping, composite lens combining, ancient will applying (see #1874)
* Hide elven trades that result in giving the same item back

Clean up JEI plugin warnings, formatting, add wrappers for a few recipe types

---

src/main/java/vazkii/botania/common/block/subtile/functional/SubTileHopperhock.java

Hopperhocks now access the inventory on e.g. the east face of the block to their west, instead of the west face of the block to their west.
This closes #2838.

Flip hopperhock inventory sidedness

---

src/main/java/vazkii/botania/api/recipe/RecipePetals.java
src/main/java/vazkii/botania/common/core/helper/ItemNBTHelper.java

This is an upstream fix of this issue in Botania Tweaks: https://github.com/quat1024/BotaniaTweaks/issues/42
The idea is that when an item has an NBT tag in a recipe, items must have *at least* those NBT tags. In other words, the NBT tag on the recipe item has to be a subset of the NBT tag on whatever item the player throws in. This makes it ok to not specify *all* the nbt tags *ever* on an item when writing recipes, which is what players would expect anyways.
However, previously this did not work properly with nested tags. An item with a tag like `{out:{in:1,extra:2}}` would match a recipe with a tag like `{}`, but would not match `{out:{in:1}}`. This creates problems when trying to create recipes for items with lots of weirdly structured NBT data (the use case in the original issue is …

Change how NBT matching works, now it's faster and works better with nested tags

---

src/main/java/vazkii/botania/client/model/FloatingFlowerModel.java
src/main/java/vazkii/botania/common/block/tile/TileFloatingFlower.java
src/main/java/vazkii/botania/common/block/tile/TileFloatingSpecialFlower.java

* First commit fixes #2844. Piston rendering uses the normal block state directly instead of the extended one, which causes the island type and the flower type properties to be null, and the table used for caching does not accept nulls causing NPEs. Moving flowers will render as if they were always on normal grass, with the placeholder flower for special ones.
* Second commit fixes something I noticed during testing this bug - applying a pasture seed to a static model flower will not show the change until the chunk section is updated. Done in basically the same manner as the petal apothecary vines.

Fix static model floating flowers crashing on moving with Quark's pistons, fix pasture seed effects not showing immediately

---

src/main/java/vazkii/botania/common/block/BlockAltGrass.java

- Fixes #2812 by special-casing stems. (I can't just check the `IPlantable` since melon/pumpkin stems and regular crops both have the `Crop` plant type, and you'd be able to plant seeds on special grass etc.)
- You can use a hoe on special grass to till it into farmland. (This is a less jank upstream merge of a [Botania Tweaks feature](https://github.com/quat1024/BotaniaTweaks/blob/master/src/main/java/quaternary/botaniatweaks/modules/botania/handler/TillAltGrassHandler.java)).

Some stuff involving special grasses

---

src/main/java/vazkii/botania/common/item/equipment/bauble/ItemDodgeRing.java
src/main/java/vazkii/botania/common/item/equipment/tool/terrasteel/ItemTerraPick.java
src/main/java/vazkii/botania/common/item/relic/ItemLokiRing.java
src/main/java/vazkii/botania/common/item/relic/ItemOdinRing.java
src/main/java/vazkii/botania/common/item/relic/ItemThorRing.java
src/main/java/vazkii/botania/common/network/PacketDodge.java

Allows compatibility with Bring Me The Rings, that changes the number of native ring slots.

Use available baubles API methods when checking for rings instead of custom made ones

---

src/main/java/vazkii/botania/api/corporea/CorporeaHelper.java

If the interceptor triggers a funnel making a request on the same network, it will overwrite the request counts with last funnel's request counts.
Despite getting 0 items from the request, the message will say that I have gotten the same amount as the last triggered funnel and had a bunch accessible.
For example, where I have a bunch of funnels requesting 1 snow and a double chest half filled with snow:
This PR swaps the order of interception and assigning this count to fix the message to correct it.

Fix corporea interceptor causing wrong count on index requests

---

src/main/java/vazkii/botania/client/core/handler/HUDHandler.java
src/main/java/vazkii/botania/common/block/BlockHourglass.java
src/main/java/vazkii/botania/common/block/corporea/BlockCorporeaCrystalCube.java
src/main/java/vazkii/botania/common/block/tile/corporea/TileCorporeaCrystalCube.java
src/main/java/vazkii/botania/common/lexicon/LexiconData.java
src/main/resources/assets/botania/lang/en_us.lang

This PR adds locking of Corporea Crystal Cubes, modeled after the Hovering Hourglass lock.
* Sneak-using a Wand of the Forest on a crystal cube will lock the monitored item, preventing players from accidentally setting it to something else. Lexicon entry page included. This is shown on the contents render and sends a chat message to the player if they attempt to set it when locked. Locking can be done with dispensers, I made sure it properly syncs to players in that case.
* Withdrawing items is not affected by the lock, in case that wasn't clear.
* Why sneak-using and not just using the wand like the hourglass? Sooner or later someone will complain they can't put the wands there.
* Rendering of the overlay for runic altars, petal apothecaries and crystal cubes is disabled if someone is …

Add corporea crystal cube locking

---

src/main/java/vazkii/botania/api/recipe/RecipePetals.java
src/main/java/vazkii/botania/common/core/helper/ItemNBTHelper.java

Mostly useful when adding CraftTweaker recipes which have Forestry bees
as inputs, since the bee's chromosomes are in a list and the recipe
only needs to match some of the item's chromosomes.
As requested here: https://github.com/quat1024/BotaniaTweaks/pull/48

When matching recipe tags, also match the first items of nested lists

---

src/main/java/vazkii/botania/common/block/tile/corporea/TileCorporeaRetainer.java

Completing a request in a corporea retainer now actually clears the comparator value of it... Fixes #2893
> who was the loser who added this bug
> `git blame`
> oh

Fix sticky comparators on corporea retainers

---

src/main/java/vazkii/botania/common/item/equipment/bauble/ItemMagnetRing.java

My mod, [Demagnetize](https://minecraft.curseforge.com/projects/demagnetize), adds a Demagnetizer that disables magnets on items around it, like the Solegnolia. 
When I released the mod originally, I added support for Botania by [hackily](https://github.com/comp500/Demagnetize/blob/master/src/main/java/link/infra/demagnetize/blocks/DemagnetizerSolegnoliaCompat.java) emulating the Solegnolia, however this completely ignores the Whitelist/Blacklist functionality in my mod. Emulation of the Solegnolia also [breaks](https://github.com/comp500/Demagnetize/issues/1) this functionality in other mods' magnets that support the Solegnolia. I intended to submit a PR to Botania to improve this, but never got around to it.
To fix this, this PR adds a check for the boolean entity NBT tag …

Improved support for Demagnetize

---

src/main/java/vazkii/botania/common/entity/EntityDoppleganger.java

Got word that the stricter arena check broke Natural Pledge's ritual because it uses blocks placed in the arena. This PR makes the gaia break blacklist also double as a list of blocks that are allowed in the arena when the fight begins, which makes sense.

Even more gaia arena stuff

---

src/main/java/vazkii/botania/api/lexicon/LexiconCategory.java
src/main/java/vazkii/botania/client/gui/lexicon/GuiLexicon.java

Adds a simple method that lets a lexicon category say if it should be displayed in the category index. The use case is quat's addon Incorporeal adding enough Corporea stuff to justify moving it to a separate category, but that means displaying an entirely empty category if the lexicon isn't upgraded yet. Doing this externally involved some pretty ugly removal and rearrangement of buttons in the index.
@quat1024 Does this appear alright for you? 🤠

Add a hook for hidden lexicon categories

---

src/main/java/vazkii/botania/client/core/handler/ContributorFancinessHandler.java
src/main/java/vazkii/botania/client/gui/lexicon/GuiLexiconIndex.java
src/main/java/vazkii/botania/client/integration/jei/runicaltar/RunicAltarRecipeCategory.java
src/main/java/vazkii/botania/common/Botania.java
src/main/java/vazkii/botania/common/block/subtile/functional/SubTileAgricarnation.java
src/main/java/vazkii/botania/common/item/ItemGrassSeeds.java
src/main/java/vazkii/botania/common/item/equipment/tool/manasteel/ItemManasteelShovel.java
src/main/java/vazkii/botania/common/lexicon/page/PageCraftingRecipe.java
src/main/java/vazkii/botania/common/lexicon/page/PageElvenRecipe.java
src/main/java/vazkii/botania/common/lexicon/page/PageManaInfusionRecipe.java
src/main/java/vazkii/botania/common/lexicon/page/PageModRecipe.java
src/main/java/vazkii/botania/common/world/ModFeatures.java
src/main/java/vazkii/botania/common/world/MysticalFlowerConfig.java
src/main/java/vazkii/botania/common/world/MysticalFlowerFeature.java
src/main/java/vazkii/botania/common/world/SkyblockWorldEvents.java
src/main/resources/data/botania/recipes/world_seed.json
src/main/resources/data/botania/tags/blocks/pebble_sources.json

* Fix GoG islands appearing below world height - world spawn is at y=-1 if there's no ground there.
* Fix tallgrass used over grass blocks. Just a renaming artifact I guess? Brought to my attention by the GoG island fix.
* Hook up flower worldgen again. Spawn rates seem to be in line with 1.12... Should this be refactored to be more like other vanilla worldgen?
* Backwards compatibility for headflowers, using the special flower tag (not a block registry lookup, because addon flowers will not be under Botania) and a map for old names. If a flower isn't found, a poppy is used instead similiarly to 1.12.
* Fix bookmark serialization for the lexicon index (I don't even know why I bookmarked the index, but I saw the exception in the log on next launch)
* Remove the debug print for JEI runic …

Various 1.14 work

---

src/main/java/vazkii/botania/client/integration/jei/JEIBotaniaPlugin.java
src/main/java/vazkii/botania/common/item/ItemLaputaShard.java
src/main/java/vazkii/botania/common/item/equipment/bauble/ItemFlightTiara.java

* JEI now seems to require a subtype interpreter for items that use NBT to even show up more than once in its interface. This makes sure that all the subtyped items actually are registered to use that.
* I added a convenience method in two of the classes where it would be useful.
* Rearranged the JEI categories to match the progression more - the new order is the progression required parts, then the three optional categories.
* The note that runic altar must be before the petal apothecary has been removed, as it's been obsoleted by both JEI and Botania changes - recipes must be manually added to a category, and rune recipes no longer extend apothecary ones.

Fix some subitems not showing up in JEI, rearrange JEI categories to make more sense

---

src/main/java/vazkii/botania/common/item/equipment/bauble/ItemBauble.java

Fixes #3026, TeamTwilight/twilightforest#836. Now it can also be used to remove items that aren't even baubles from those slots, if for some reason you have those in there.

[1.12] Fix exception on equipping Botania baubles over cap-only baubles

---

src/main/java/vazkii/botania/common/lexicon/page/PageEntity.java
src/main/java/vazkii/botania/common/lexicon/page/PageShedding.java

Fixes #2631, fixes #2909, fixes #3036. Null item stacks, 3 years after the release of 1.11. 
As for the second part, I had to compare the code with Patchouli... OpenGlHelper vs GlStateManager, who would win?
Includes some minor cleanups that won't matter in a week, like rawtypes on the entity page construction.

[1.12] Fix shedding page NPE, fix entity render making the world fullbright

---

src/main/java/vazkii/botania/common/item/ItemLexicon.java

Fixes #2988. This also guards against throwing the lexicon/switching the slot in the short 5 tick window.

[1.12] Fix lexicon share crashing if you don't have the lexicon in main hand

---

src/main/java/vazkii/botania/api/corporea/CorporeaHelper.java
src/main/java/vazkii/botania/api/corporea/CorporeaRequest.java
src/main/java/vazkii/botania/api/corporea/CorporeaRequestDefaultMatchers.java
src/main/java/vazkii/botania/api/corporea/CorporeaRequestEvent.java
src/main/java/vazkii/botania/api/corporea/CorporeaRequestMatcher.java
src/main/java/vazkii/botania/api/corporea/ICorporeaInterceptor.java
src/main/java/vazkii/botania/api/corporea/ICorporeaRequestMatcher.java
src/main/java/vazkii/botania/api/corporea/ICorporeaRequestor.java
src/main/java/vazkii/botania/common/block/tile/corporea/TileCorporeaCrystalCube.java
src/main/java/vazkii/botania/common/block/tile/corporea/TileCorporeaFunnel.java
src/main/java/vazkii/botania/common/block/tile/corporea/TileCorporeaIndex.java
src/main/java/vazkii/botania/common/block/tile/corporea/TileCorporeaInterceptor.java
src/main/java/vazkii/botania/common/block/tile/corporea/TileCorporeaRetainer.java
src/main/java/vazkii/botania/common/integration/corporea/WrappedIInventory.java
src/main/java/vazkii/botania/common/integration/corporea/WrappedInventoryBase.java

Notes:
- This breaks some API stuff (sorry, getInventoriesWithItemInNetwork), but that's OK because nobody's written a 1.14 addon for Botania anyway
- This also makes existing Retainers lose their currently-remembered requests (but AFAIK they're broken on HEAD rn anyway)
- I put the current matchers in static subclasses CorporeaRequestDefaultMatchers for the sake of compactness and `import static` them; if this style isn't OK I can split them up too
- Yes, I know the serialization mechanic for TileCorporeaRetainer is clunky. But it works, I'm pretty sure. (Couldn't test; see above note about them being broken)

Overhaul Corporea to pass around CorporeaRequestMatchers instead of Objects

---

src/main/java/vazkii/botania/api/BotaniaAPI.java
src/main/java/vazkii/botania/api/item/IExoflameHeatable.java
src/main/java/vazkii/botania/common/Botania.java
src/main/java/vazkii/botania/common/block/subtile/functional/SubTileExoflame.java
src/main/java/vazkii/botania/common/block/tile/mana/TileBellows.java
src/main/java/vazkii/botania/common/capability/NoopCapStorage.java
src/main/java/vazkii/botania/common/capability/NoopExoflameHeatable.java
src/main/java/vazkii/botania/common/capability/SimpleCapProvider.java
src/main/java/vazkii/botania/common/core/handler/ExoflameFurnaceHandler.java
src/main/java/vazkii/botania/common/integration/curios/CurioIntegration.java

* Added a simple cap provider, and moved the curio integration to use that.
* Converted exoflame heating to a cap, and furnace heating is now an implementation of that cap.
* Converted the code to use method handles. Seems like a very easy performance improvement, gave me like 4 times better tick times on exoflame tick, going from ~700 microseconds to ~150. Also caching the last recipe for the cap, something that I am amazed Mojang didn't do. 
* Moved the one furnace-specific method used by bellows into there, adjusted to use method handles instead of reflection.

Move exoflame heatable to a cap, convert furnace part to use it

---

src/main/java/vazkii/botania/api/recipe/RecipeElvenTrade.java
src/main/java/vazkii/botania/client/integration/jei/JEIBotaniaPlugin.java
src/main/java/vazkii/botania/common/block/tile/TileAlfPortal.java
src/main/java/vazkii/botania/common/crafting/ModElvenTradeRecipes.java

The lexicon recipe is now a normal recipe, it displays in JEI too. Elven trades can now modify their outputs based on the inputs, and define if the item is used in the recipe for the early entry check. Also portals won't try to match items at all if they are empty.

Un-specialcase elven lexicon recipe, improve elven trade api

---

src/main/resources/data/botania/advancements/challenge/gaia_guardian_hardmode.json
src/main/resources/data/botania/recipes/cacophonium.json

* Cacophonium recipe now no longer tries to make use of brass if that's not available.
* GG2 advancement now checks killing it instead of binding dice that didn't work outside of cheating dice in.

Fix gaia guardian hardmode advancement and cacophonium recipe

---

src/main/java/vazkii/botania/common/core/loot/LootHandler.java

After a quick consultation, turns out loot pools need to be named and no one tells you about it. Thanks Nooby <3
Fixes #3066.

Fix injected loot pool being unnamed, fixes #3066

---

src/main/java/vazkii/botania/api/corporea/CorporeaIndexRequestEvent.java
src/main/java/vazkii/botania/api/corporea/CorporeaRequestDefaultMatchers.java
src/main/java/vazkii/botania/api/corporea/ICorporeaRequestMatcher.java
src/main/java/vazkii/botania/client/core/handler/CorporeaInputHandler.java
src/main/java/vazkii/botania/common/block/tile/corporea/TileCorporeaIndex.java
src/main/java/vazkii/botania/common/lib/LibObfuscation.java
src/main/java/vazkii/botania/common/network/PacketHandler.java
src/main/java/vazkii/botania/common/network/PacketIndexKeybindRequest.java

One issue I always had with Corporea Index requesting is that it often ends up requesting an item that has the same name, but isn't actually the same thing. Nether bricks, mushrooms, enchanted books are all good examples of it in 1.12. This PR makes keybind requests send an item stack.
* Keybind requests now send an itemstack instead of the item name. Items in inventories ignore their own NBT, JEI/recipe book items don't. The NBT matching was made less strict. (is full strictness desirable sometimes? This uses the logic from #2881.)
* Chat is no longer touched by keybind requests, fixes #2942.
* Recipe book buttons can now be a source of keybind requests, fixes #3052. 
* Keybind requests work again with shift and ctrl.
* Matchers are in charge of their index request formatting.
* Index …

Improve Corporea Index keybind requests to not use chat

---

src/main/resources/assets/botania/lang/en_us.json
web/module/lexicon.php

Makes the web-lexicon handle internal Patchouli links properly.
Unfortunately, there's no generated database mapping patchouli-entries to lang-file names, so it's… not the most performant. (Uses about eight file_get_contents.).

Improve lexicon.php to handle Lexica crosslinks

---

src/main/resources/data/forge/tags/blocks/storage_blocks.json
src/main/resources/data/forge/tags/blocks/storage_blocks/elementium.json
src/main/resources/data/forge/tags/blocks/storage_blocks/manasteel.json
src/main/resources/data/forge/tags/blocks/storage_blocks/quartz.json
src/main/resources/data/forge/tags/blocks/storage_blocks/terrasteel.json
src/main/resources/data/forge/tags/items/storage_blocks.json
src/main/resources/data/forge/tags/items/storage_blocks/elementium.json
src/main/resources/data/forge/tags/items/storage_blocks/manasteel.json
src/main/resources/data/forge/tags/items/storage_blocks/quartz.json
src/main/resources/data/forge/tags/items/storage_blocks/terrasteel.json

Add Terrasteel, Manasteel and Elementium Blocks to their own storage_blocks tag and the quartz variant blocks to forge:storageblocks/quartz.

Add some block tags for compatibility

---

src/main/resources/data/botania/recipes/brewery.json
src/main/resources/data/botania/recipes/conversions/elementium_block_deconstruct.json
src/main/resources/data/botania/recipes/conversions/manasteel_block_deconstruct.json
src/main/resources/data/botania/recipes/conversions/terrasteel_block_deconstruct.json
src/main/resources/data/botania/recipes/spawner_claw.json
src/main/resources/data/botania/recipes/terra_pick.json
src/main/resources/data/botania/recipes/terra_plate.json
src/main/resources/data/botania/recipes/terrasteel_boots.json
src/main/resources/data/botania/recipes/terrasteel_chestplate.json
src/main/resources/data/botania/recipes/terrasteel_helmet.json
src/main/resources/data/botania/recipes/terrasteel_helmet_revealing.json
src/main/resources/data/botania/recipes/terrasteel_leggings.json

Change the Terrasteel armor recipes to use the Terrasteel ingot tag instead of the item,
and change some recipes to use the Block tags from #3079

Change some Recipes to use Tags

---

web/module/lexicon.php

Fix the website lexicon page "bleeding-edge lang file" link to the github lang file, as it still linkes to a not existing en_US.lang one.

Fix the "bleeding-edge lang file" link

---

src/main/java/vazkii/botania/common/block/BlockPistonRelay.java

See https://github.com/Vazkii/Botania/issues/3180
Turns out the problem lied in the fact that only the OW state was being saved, and other dimensions', modded or vanilla, wasn't.

Allow force relays to store their bound blocks on other dimensions

---

src/main/java/vazkii/botania/common/block/tile/TileAltar.java

I came across this earlier today and was thoroughly annoyed when attempting to recraft in creative proved more difficult that it should be. Curretnly, reinserting a recipe required and removed the items from the player's inventory, creative mode or not. With this change, reinserting a recipe, while still requiring at least one of each item, no longer removes those items from the inventory.
Should reinserting a recipe from creative mode instead not require even the presence of materials?

Don't reduce stack size when re-adding previous recipe in creative.

---

src/main/java/vazkii/botania/client/core/handler/TooltipAdditionDisplayHandler.java

Terra Shatterer and Mana Tablet/Band tooltips are no longer black, and the rank text of the Terra Shatterer tooltip no longer appears behind other items.

Fix some tooltips.

---

src/generated/resources/data/botania/loot_tables/blocks/black_double_flower.json
src/generated/resources/data/botania/loot_tables/blocks/blue_double_flower.json
src/generated/resources/data/botania/loot_tables/blocks/brown_double_flower.json
src/generated/resources/data/botania/loot_tables/blocks/cyan_double_flower.json
src/generated/resources/data/botania/loot_tables/blocks/gray_double_flower.json
src/generated/resources/data/botania/loot_tables/blocks/green_double_flower.json
src/generated/resources/data/botania/loot_tables/blocks/light_blue_double_flower.json
src/generated/resources/data/botania/loot_tables/blocks/light_gray_double_flower.json
src/generated/resources/data/botania/loot_tables/blocks/lime_double_flower.json
src/generated/resources/data/botania/loot_tables/blocks/magenta_double_flower.json
src/generated/resources/data/botania/loot_tables/blocks/orange_double_flower.json
src/generated/resources/data/botania/loot_tables/blocks/pink_double_flower.json
src/generated/resources/data/botania/loot_tables/blocks/purple_double_flower.json
src/generated/resources/data/botania/loot_tables/blocks/red_double_flower.json
src/generated/resources/data/botania/loot_tables/blocks/white_double_flower.json
src/generated/resources/data/botania/loot_tables/blocks/yellow_double_flower.json
src/generated/resources/data/forge/tags/items/shears.json
src/main/java/vazkii/botania/common/lib/ModTags.java
src/main/java/vazkii/botania/data/BlockLootProvider.java
src/main/java/vazkii/botania/data/ItemTagProvider.java

This PR adds the support of shears of other mods with "forge:shears" tag & adds additionally manasteel and elementium shears to loot tables of double flowers

Support mod shears

---

src/main/java/vazkii/botania/common/block/BlockAltar.java

let apothecary be more compatible with other fluid containers
- filling apothecary with lava works like filling with water
- emptying apothecary with fluid containers also possible now
Edit: Can be tested with mods like [Ceramic Bucket](https://www.curseforge.com/minecraft/mc-mods/ceramic-bucket) or [Big Buckets](https://www.curseforge.com/minecraft/mc-mods/bigbuckets).

apothecary more compatible with other fluid containers

---

src/main/java/vazkii/botania/common/item/lens/LensMagnet.java

This should preserve the peculiarities of the previous logic, while fixing the unreported bug where bursts not fired from Mana Spreaders would not magnetize block around the origin.

Make Magnet Lens code better but actually worse if you're a masochist.

---

src/main/java/vazkii/botania/api/brew/Brew.java

The current Brew class is unable to create Brews using Effects that are registered through DeferredRegisters. By adding a supplier and modifying various fields to only use the EffectaInstance when needed through suppliers, Minecraft will not crash when trying to register a Brew using effects from other mods. 
I ran into this issue when I was trying to add brews when Botania is installed for my mod and am currently using a workaround to bypass the crash.
https://github.com/MinerArcana/Astral/compare/feature/botania_compat#diff-f4145c9694231af724e6a15feceb81e8

Add alternative constructor to accept suppliers for EffectInstances

---

src/main/java/vazkii/botania/common/block/subtile/generating/SubTileRafflowsia.java
src/main/java/vazkii/botania/data/BlockLootProvider.java
src/main/resources/assets/botania/lang/en_us.json

Single-flower repetition is nerfed _heavily_, but flower will now output up to 100k per flower for a streak of length 40.
You want to automate this? Good luck.

Overhaul Rafflowsia to scale with flower variety

---

src/main/java/vazkii/botania/common/entity/EntityCorporeaSpark.java
src/main/java/vazkii/botania/common/entity/ModEntities.java
src/main/java/vazkii/botania/common/item/ItemCorporeaSpark.java
src/main/java/vazkii/botania/common/item/ItemSpark.java
src/main/java/vazkii/botania/common/item/lens/LensPaint.java

Currently checks against `EntitySparkBase` because `ISpark` and `ICorporeaSpark`, despite their names, are disjoint
when testing i noticed that horizontally-fired bursts are at "eye-level" with the bottoms of sparks, so if you'd like to nudge those downward for reliable collisions, i can do that

Allow paintslinger lens to dye sparks

---

src/main/java/vazkii/botania/common/Botania.java
src/main/java/vazkii/botania/common/block/subtile/generating/SubTileEntropinnyum.java

Fixes #3426.
The current solution is to:
- make the whole thing static instead of per Entro because that's terrible all over
- always write the tag, write false if the TNT is ethical, true if it's unethical
- check if the TNT already has the tag before checking whether it's ethical
That should fix the issue ever coming up again, in worlds after this update.
However:
- worlds with Botania just added/updated with TNTs already in the world may still run into the issue
To circumvent that another check has been added:
- if the fuse is already below the max, don't bother checking
However this will still have issues from updating worlds with TNT's that haven't ticked at all since spawning.

Improve TNT ethics, fix world-loading deadlock.

---

src/main/java/vazkii/botania/api/item/ISortableTool.java
src/main/java/vazkii/botania/common/item/equipment/bauble/ItemSwapRing.java
src/main/java/vazkii/botania/common/item/equipment/tool/ItemGlassPick.java
src/main/java/vazkii/botania/common/item/equipment/tool/manasteel/ItemManasteelAxe.java
src/main/java/vazkii/botania/common/item/equipment/tool/manasteel/ItemManasteelPick.java
src/main/java/vazkii/botania/common/item/equipment/tool/manasteel/ItemManasteelShovel.java

This PR ensures that the Vitreous Pickaxe is swapped for by the Ring of Correction when breaking glass. The previous behaviour was that it would always be swapped out.
Here it is after the changes:
https://user-images.githubusercontent.com/11538216/103090080-ef54b500-45e7-11eb-8ea3-67cae6c33ab6.mp4

Prioritize Vitreous Pickaxe for the Ring of Correction when breaking glass

---

src/main/java/vazkii/botania/api/mana/ManaItemHandler.java
src/main/java/vazkii/botania/common/impl/mana/ManaItemHandlerImpl.java
src/main/java/vazkii/botania/common/item/rod/ItemCobbleRod.java
src/main/java/vazkii/botania/common/item/rod/ItemDirtRod.java
src/main/java/vazkii/botania/common/item/rod/ItemTerraformRod.java

- provideBlock was not respecting doit=false as a full check of capability
- getBlockCount providing a -1 sentinel for "infinite" is not accurate when the capability is in fact not infinite but dependent on mana availability.
- Refactored a little bit in ManaItemHandlerImpl to avoid code duplication.
- That refactoring revealed that requestManaForTool was un-discounting for some undocumented reason.  The function appears unused internally anyway, and I cannot think of any reason why it would undo the discount, so I nuked that.

Fully implementing IBlockProvider on rods

---

src/generated/resources/data/botania/recipes/dynamic/split_lens.json
src/main/java/vazkii/botania/api/mana/ILens.java
src/main/java/vazkii/botania/common/crafting/recipe/SplitLensRecipe.java
src/main/java/vazkii/botania/common/item/ModItems.java
src/main/java/vazkii/botania/common/item/lens/ItemLens.java
src/main/java/vazkii/botania/data/recipes/RecipeProvider.java

This PR implements a recipe that allows splitting composite lenses into their component lenses.
The slime ball is lost, but the two lenses are recovered.

Add lens splitting recipe

---

src/generated/resources/data/botania/advancements/recipes/botania/fabulous_pool_upgrade.json
src/generated/resources/data/botania/recipes/fabulous_pool_upgrade.json
src/main/java/vazkii/botania/data/recipes/RecipeProvider.java
src/main/resources/data/botania/patchouli_books/lexicon/en_us/entries/tools/rainbow_rod.json

Not sure if this is okay to add, close PR if it is not good (and sorry for wasting time ;-;)
Also added the recipe to the lexicon, but it made the text a bit too close to the bottom of the page.
Perhaps this should be on another page? Will change if so, let me know.
<details>
<summary>Screenshots</summary>
</details>

Add recipe upgrading to Fabulous Pool from Mana Pool

---

src/main/java/vazkii/botania/client/render/tile/RenderTileTinyPotato.java

While this proof may not be particularly formal, it should hopefully be adequate.
I believe that the highlighted statement here
```patch
@@ -271,7 +271,6 @@ private void renderName(TileTinyPotato potato, String name, MatrixStack ms, IRen
ms.rotate(mc.getRenderManager().getCameraOrientation());
float f1 = 0.016666668F * 1.6F;
ms.scale(-f1, -f1, f1);
-			ms.translate(0.0F, 0F / f1, 0.0F);
int halfWidth = mc.fontRenderer.getStringWidth(potato.name.getString()) / 2;
float opacity = Minecraft.getInstance().gameSettings.getTextBackgroundOpacity(0.25F);
```
is redundant.
Firstly, it is necessary to realize that the expression `0F / f1` evaluates to `0`. That is because the value `f1` is the constant expression `0.016666668F * 1.6F`. Substituting that expression into the former results in `0F / …

Remove a redundant translation

---

src/main/java/vazkii/botania/client/lib/LibResources.java
src/main/java/vazkii/botania/client/render/tile/RenderTileTinyPotato.java

Somehow there was an extra `/` appearing in model names when iterating over the resource locations. This PR fixes that.
???
---

Fix tiny potato models not working with resource packs

---

src/main/resources/assets/botania/shader/halo.frag

**Before the changes**
https://user-images.githubusercontent.com/11804768/114567336-8605ba00-9c49-11eb-9f37-c904111f58f6.mp4
**After the changes**
https://user-images.githubusercontent.com/11804768/114567400-974ec680-9c49-11eb-8e96-a6990b6afe73.mp4
This does not have a visible change on the Babylon key attack or the tiara's halo for what I tested.
This Fixes #3638

Makes luminizer shaders not square

---

src/main/java/vazkii/botania/api/BotaniaAPI.java
src/main/java/vazkii/botania/api/item/IHornHarvestable.java
src/main/java/vazkii/botania/common/block/ModBlocks.java
src/main/java/vazkii/botania/common/block/decor/BlockModMushroom.java
src/main/java/vazkii/botania/common/block/decor/BlockShinyFlower.java
src/main/java/vazkii/botania/common/impl/BotaniaAPIImpl.java
src/main/java/vazkii/botania/common/impl/DefaultHornHarvestable.java
src/main/java/vazkii/botania/common/item/ItemHorn.java

This removes the need to explicitly implement the interface in block classes.

Add API method to register IHornHarvestable instances

---

src/main/java/vazkii/botania/common/integration/crafttweaker/RuneAltarRecipeManager.java

Without it we can't generate an example for it, so on the docs it looks like:
```zenscript
RuneAltar.addRecipe(name as string, output as IItemStack, mana as int, inputs as IIngredient[]) as void
```
instead of
```
<recipetype:botania:runic_altar>.addRecipe("petal_apothecary_test", <item:minecraft:diamond>, 5000, <item:botania:rune_>, <item:botania:orange_petal>, <item:botania:red_petal>);
```

Added a missing doc param to the rune altar

---

src/main/java/vazkii/botania/common/core/loot/ModLootModifiers.java
src/main/java/vazkii/botania/common/core/loot/RealPlayerCondition.java
src/main/java/vazkii/botania/common/entity/EntityDoppleganger.java
src/main/java/vazkii/botania/common/item/relic/ItemDice.java
src/main/resources/data/botania/loot_tables/dice/roll_1.json
src/main/resources/data/botania/loot_tables/dice/roll_2.json
src/main/resources/data/botania/loot_tables/dice/roll_3.json
src/main/resources/data/botania/loot_tables/dice/roll_4.json
src/main/resources/data/botania/loot_tables/dice/roll_5.json
src/main/resources/data/botania/loot_tables/dice/roll_6.json
src/main/resources/data/botania/loot_tables/gaia_guardian.json
src/main/resources/data/botania/loot_tables/gaia_guardian/lotuses.json
src/main/resources/data/botania/loot_tables/gaia_guardian/materials.json
src/main/resources/data/botania/loot_tables/gaia_guardian/runes.json
src/main/resources/data/botania/loot_tables/gaia_guardian_2.json

Submitting for feedback, mostly.
cc @williewillus @Alwinfy
* a bit of anticheese
* more loot: dice of fate give spirits and some more random stuff once out of relics, because people dislike having to grind the guardian (not our fault, really, but modpack authors sometimes don't playtest their own grind)
* a bit of niceties: nerfing health in multiplayer by a bunch, killing pixies and clearing wither on death of the guardian, bumping the damage cap, and triggering win advancements for everyone involved, not just the true killer
Any of this anticheese is overkill? Anything to tweak?

Gaia guardian tweaks

---

src/generated/resources/assets/botania/models/block/corporea_index.json
src/main/java/vazkii/botania/client/render/tile/RenderTileCorporeaIndex.java
src/main/java/vazkii/botania/client/render/tile/TEISR.java
src/main/java/vazkii/botania/common/block/corporea/BlockCorporeaIndex.java
src/main/java/vazkii/botania/common/block/tile/corporea/TileCorporeaIndex.java
src/main/java/vazkii/botania/data/BlockstateProvider.java
src/main/resources/assets/botania/models/block/corporea_crystal_cube.json

* Fix the math in `RenderTileCorporeaIndex` to add `partialTicks` to the global tick count *before* multiplying it by 2, this makes it not jitter so much
* Pass `ClientTickHandler.partialTicks` through in `TEISR`, everything that uses it now animates smoother. The Botanical Brewery looks a lot nicer now
* Allow the corporea index TEISR to rotate as well. Why not?
* Add a custom render bounding box to the corporea index, so the pink particles don't get prematurely culled when looking away. (I think this method is a forge extension unfortunately)
* Use more fitting particle textures for the corporea index (and corporea crystal cube) since it was bugging me
Also I wanted to fix the AO acting strange on corporea indices (try placing 9 of them in a square, it makes the floor turn black), but I …

Make the corporea index look better (+ some other stuff)

---

src/main/java/vazkii/botania/mixin/MixinDetectorRailBlock.java

This fixes the mixin responsible for crashing the game at startup with built jars. This doesn't happen in dev environments, only with a built jar. I tested to ensure the behaviour is still correct.

Fixed the issue with the built jar

---

src/main/java/vazkii/botania/common/block/mana/BlockSpreader.java

* Spreaders only consume right-clicks if something actually happened (adding/removing a lens, etc)
* Wool isn't removed from your inventory when decorating a spreader in creative mode.
* Wool can be removed by clicking with more wool (idk about this actually, but it makes things in creative mode easier)
* Wool makes sounds when being placed and removed.

Tweaks to right-click interactions with spreaders
